import fs from 'node:fs';
import assert from 'node:assert/strict';
import * as THREE from 'three';
import {RAPIER,Physics} from '../preview/runtime/physics.js';
import {PhysicsVehicle} from '../preview/runtime/PhysicsVehicle.js';
import {Events} from '../preview/runtime/Events.js';
import {LoopAssist} from '../preview/runtime/loop.js';
import {readGLB} from './read_glb.mjs';
await RAPIER.init();const {scene,nodes,doc}=readGLB('exports/AlejandroWorld.glb');const physics=new Physics();physics.scene=scene;
function animated(o){for(;o;o=o.parent)if(o.userData.animated)return true;return false;}
const roots=[];scene.traverse(o=>{if(o.userData.collision&&!animated(o)){let owned=false;for(let p=o.parent;p;p=p.parent)if(p.userData.collision)owned=true;if(!owned)roots.push(o);}});
for(const o of roots)physics.mesh(o);
const ticker={events:new Events(),elapsed:0,deltaScaled:1/60,scale:1};ticker.events.on('fixed',()=>physics.step(),3);const v=new PhysicsVehicle(physics,ticker,{add(){}},{x:-200,y:1.2,z:44});v.topSpeed=15;v.surfaceFriction=c=>c?.userData?.surface_type==='ice'?.025:1.3;
const nav=JSON.parse(fs.readFileSync('exports/navigation.json'));const loop=new LoopAssist(v,nav.loop.points);ticker.events.on('fixed',()=>loop.beforeStep(),1);
function steps(n){for(let i=0;i<n;i++){ticker.elapsed+=1/60;ticker.events.trigger('fixed');}}
const results=[];
function test(name,f){try{const data=f();results.push({name,passed:true,data});console.log('PASS',name,JSON.stringify(data));}catch(e){results.push({name,passed:false,error:e.message});console.error('FAIL',name,e.message);}}
function reset(pos){loop.reset();v.input.accelerating=0;v.input.braking=0;v.input.boosting=0;v.input.steering=0;v.moveTo(pos);steps(90);}
test('GLB embeds all image data and animated Ferris wheel',()=>{assert(doc.images.every(i=>i.bufferView!==undefined||i.uri?.startsWith('data:')));assert(doc.animations?.length);const duration=Math.max(...doc.animations.flatMap(a=>a.samplers.map(s=>doc.accessors[s.input].max[0])));assert(Math.abs(duration-30)<.001);const dynamic=physics.dynamic.filter(p=>p.node);assert(dynamic.length>=25);return {nodes:nodes.length,animationDuration:duration,animations:doc.animations.map(a=>a.name),dynamicProps:dynamic.length,colliders:physics.world.colliders.len()};});
test('Penguins stay upright at rest until struck',()=>{steps(600);const penguins=physics.dynamic.filter(p=>p.node?.name.startsWith('PlasticPenguin_0'));const upright=penguins.filter(p=>new THREE.Quaternion().copy(p.body.rotation()).angleTo(p.home.quaternion)<.35);assert(upright.length>=6,JSON.stringify(penguins.map(p=>({name:p.node.name,angle:new THREE.Quaternion().copy(p.body.rotation()).angleTo(p.home.quaternion)}))));return {upright:upright.length,total:penguins.length,seconds:10};});
test('Vehicle accelerates on actual circuit triangles',()=>{reset({x:-201,y:1.2,z:44});v.input.accelerating=1;steps(120);assert(v.position.x>-195);assert(v.wheels.inContactCount>=2);return {position:v.position.toArray(),speed:v.speed,contacts:v.wheels.inContactCount};});
let asphalt,ice;
function braking(position){reset(position);v.chassis.physical.body.setLinvel({x:8,y:0,z:0},true);v.input.braking=1;const start=v.position.clone();let surfaces=new Set();for(let i=0;i<60;i++){steps(1);for(const w of v.wheels.items)if(w.groundCollider)surfaces.add(w.groundCollider.userData?.surface_type);}return {distance:v.position.distanceTo(start),endSpeed:v.speed,surfaces:[...surfaces],contacts:v.wheels.inContactCount};}
test('Ice measurably reduces braking compared with asphalt',()=>{asphalt=braking({x:-202,y:1.2,z:44});ice=braking({x:16,y:1.2,z:-136});assert(ice.surfaces.includes('ice'),JSON.stringify(ice));assert(ice.distance>asphalt.distance*1.8,JSON.stringify({asphalt,ice}));assert(ice.endSpeed>asphalt.endSpeed+1);return {asphalt,ice};});
test('Vehicle pushes a plastic penguin with real rigid-body contact',()=>{physics.resetProps();const prop=physics.dynamic.find(p=>p.node?.name.startsWith('PlasticPenguin_01'));assert(prop);reset({x:prop.home.position.x-6,y:1.3,z:prop.home.position.z});const before=new THREE.Vector3().copy(prop.body.translation());v.chassis.physical.body.setLinvel({x:7,y:0,z:0},true);v.input.accelerating=1;steps(100);const after=new THREE.Vector3().copy(prop.body.translation());const moved=before.distanceTo(after);assert(moved>1,JSON.stringify({moved,home:prop.home.position.toArray(),before:before.toArray(),after:after.toArray(),car:v.position.toArray(),speed:v.speed}));return {moved_m:moved,mass:prop.body.mass()};});
test('Vehicle pushes a light cone',()=>{physics.resetProps();const prop=physics.dynamic.find(p=>p.node?.name.startsWith('Ice_slalom')||p.node?.name.startsWith('Ice slalom'));assert(prop);reset({x:prop.home.position.x-5,y:1.3,z:prop.home.position.z});const before=new THREE.Vector3().copy(prop.body.translation());v.chassis.physical.body.setLinvel({x:7,y:0,z:0},true);v.input.accelerating=1;steps(100);const after=new THREE.Vector3().copy(prop.body.translation());const moved=before.distanceTo(after);assert(moved>.8,JSON.stringify({moved,home:prop.home.position.toArray(),before:before.toArray(),after:after.toArray(),car:v.position.toArray(),speed:v.speed}));return {moved_m:moved,mass:prop.body.mass()};});
test('Vertical loop traversal and wheel contact with local adhesion',()=>{reset({x:-29,y:1.2,z:141});v.chassis.physical.body.setLinvel({x:19,y:0,z:0},true);v.input.accelerating=1;v.input.boosting=1;const before=loop.completed;let maxHeight=0;for(let i=0;i<360;i++){steps(1);maxHeight=Math.max(maxHeight,v.position.y);if(loop.completed>before)break;}const fraction=loop.contactSamples.filter(n=>n>=2).length/Math.max(1,loop.contactSamples.length);assert(loop.completed>before,JSON.stringify({active:loop.active,index:loop.index,pos:v.position.toArray(),maxHeight}));assert(maxHeight>17);assert(fraction>.6,`wheel contact fraction ${fraction}`);return {completed:loop.completed,maxHeight,wheelContactFraction:fraction,samples:loop.contactSamples.length};});
fs.writeFileSync('reports/physics-tests.json',JSON.stringify(results,null,2));console.log(`${results.filter(r=>r.passed).length}/${results.length} passed`);if(results.some(r=>!r.passed))process.exitCode=1;
