import fs from 'node:fs';import assert from 'node:assert/strict';import * as THREE from 'three';
import {Physics,RAPIER} from '../preview/runtime/physics.js';import {PhysicsVehicle} from '../preview/runtime/PhysicsVehicle.js';import {Events} from '../preview/runtime/Events.js';import {LoopAssist} from '../preview/runtime/loop.js';import {tuneVehicle} from '../preview/runtime/driving.js';import {readGLB} from './read_glb.mjs';
await RAPIER.init();const {scene,doc,nodes}=readGLB('exports/AlejandroWorld.glb'),physics=new Physics();physics.scene=scene;const nav=JSON.parse(fs.readFileSync('exports/navigation.json'));const roots=[];const animated=o=>{for(;o;o=o.parent)if(o.userData.animated)return true;return false;};scene.traverse(o=>{if(o.userData.collision&&!animated(o)){let own=false;for(let p=o.parent;p;p=p.parent)if(p.userData.collision)own=true;if(!own)roots.push(o);}});for(const o of roots)physics.mesh(o);
const ticker={events:new Events(),elapsed:0,deltaScaled:1/30,scale:2};ticker.events.on('fixed',()=>physics.step(),3);const v=new PhysicsVehicle(physics,ticker,{add(){}},{x:12,y:1.3,z:20});tuneVehicle(v);const loop=new LoopAssist(v,nav.loop.points);ticker.events.on('fixed',()=>loop.beforeStep(),1);
const vec=p=>new THREE.Vector3(p[0],p[2],-p[1]);function step(n=1){for(let i=0;i<n;i++){ticker.elapsed+=1/30;ticker.events.trigger('fixed');}}
function reset(p,angle=0){loop.reset();Object.assign(v.input,{accelerating:0,braking:0,boosting:0,steering:0});v.moveTo(p,angle);step(60);}
const results=[];function test(name,fn){try{const data=fn();results.push({name,passed:true,data});console.log('PASS',name,JSON.stringify(data));}catch(e){results.push({name,passed:false,error:e.message});console.log('FAIL',name,e.message);}}
test('Portable compact world and synchronized wheel',()=>{assert(doc.images.every(i=>i.bufferView!==undefined||i.uri?.startsWith('data:')));const duration=Math.max(...doc.animations.flatMap(a=>a.samplers.map(s=>doc.accessors[s.input].max[0])));assert(Math.abs(duration-30)<.001);assert(nav.roads.length>=4);return {nodes:nodes.length,duration,bodyCount:physics.world.bodies.len(),dynamicProps:physics.dynamic.length-1};});
test('Exact Portfolio scale, timestep and World2 handling',()=>{step(1);assert.equal(v.boostMultiplier,.6);assert.equal(v.topSpeedBoost,22);assert.equal(v.topSpeed,5);assert.equal(ticker.scale,2);assert(Math.abs(physics.world.timestep-1/30)<1e-7);assert(Math.abs(v.chassis.physical.body.localCom().y+.9)<.001,JSON.stringify(v.chassis.physical.body.localCom()));return {mass:v.chassis.mass,COM:v.chassis.physical.body.localCom(),width:1.7,boulevardWidth:7.6};});
test('Eight physical penguins stand at rest',()=>{step(300);const a=physics.dynamic.filter(p=>p.node?.name.startsWith('Learner penguin'));const stable=a.filter(p=>new THREE.Quaternion().copy(p.body.rotation()).angleTo(p.home.quaternion)<.35);assert.equal(stable.length,8,JSON.stringify(a.map(p=>({name:p.node.name,y:p.body.translation().y,angle:new THREE.Quaternion().copy(p.body.rotation()).angleTo(p.home.quaternion)}))));return {upright:stable.length,total:a.length};});
function brake(p){reset(p);v.chassis.physical.body.setLinvel({x:8,y:0,z:0},true);v.input.braking=1;const start=v.position.clone(),surfaces=new Set();for(let i=0;i<40;i++){step();for(const w of v.wheels.items)if(w.groundCollider)surfaces.add(w.groundCollider.userData.surface_type);}return {distance:v.position.distanceTo(start),speed:v.speed,surfaces:[...surfaces]};}
test('Ice reduces braking through the same controller hook',()=>{const road=brake({x:-43,y:1.3,z:71}),ice=brake({x:-40,y:2.6,z:-65});assert(ice.surfaces.includes('ice'));assert(ice.distance>road.distance*1.5,JSON.stringify({road,ice}));return {road,ice};});
for(const prefix of ['Learner penguin','Ice cone'])test('Car physically pushes '+prefix,()=>{physics.resetProps();const prop=physics.dynamic.find(p=>p.node?.name.startsWith(prefix));reset({x:prop.home.position.x-5,y:prop.home.position.y+1,z:prop.home.position.z});const before=new THREE.Vector3().copy(prop.body.translation());v.input.accelerating=1;step(100);const moved=before.distanceTo(new THREE.Vector3().copy(prop.body.translation()));assert(moved>.7,'moved '+moved);return {moved};});
function follow(points,{closed=false,laps=1,speed=7,maxFrames=20000,resetStart=true,enterLoop=false}={}){const ps=points.map(vec),first=ps[1].clone().sub(ps[0]);if(resetStart)reset(ps[0].clone().add(new THREE.Vector3(0,1.2,0)),Math.atan2(-first.z,first.x));let index=0,travel=0,maxError=0,air=0;const path=[];
 for(let frame=0;frame<maxFrames;frame++){
  let nearest=index,d=Infinity;for(let j=index;j<Math.min(ps.length,index+14);j++){const n=v.position.clone().setY(ps[j].y).distanceToSquared(ps[j]);if(n<d){d=n;nearest=j;}}index=nearest;maxError=Math.max(maxError,Math.sqrt(d));
  if(enterLoop&&loop.active)return {frames:frame,maxError,air,position:v.position.toArray(),path};
  if(index>=ps.length-3)return {frames:frame,maxError,air,position:v.position.toArray(),path};
  let look=index,length=0;while(look<ps.length-1&&length<Math.max(4,v.speed*.5)){length+=ps[look+1].distanceTo(ps[look]);look++;}
  const target=ps[look].clone().sub(v.position);let desired=Math.atan2(-target.z,target.x),current=Math.atan2(-v.forward.z,v.forward.x),err=Math.atan2(Math.sin(desired-current),Math.cos(desired-current));v.input.steering=THREE.MathUtils.clamp(err*2.2,-1,1);const wanted=speed/(1+Math.abs(err)*1.5);v.input.accelerating=v.speed<wanted?.28:0;v.input.braking=v.speed>wanted+.5?.25:0;v.input.boosting=enterLoop&&index>ps.length-35?1:0;if(enterLoop&&index>ps.length-35){v.input.accelerating=1;v.input.braking=0;}step();if(v.wheels.inContactCount<2)air++;if(frame%30===0)path.push(v.position.toArray());if(v.position.y<-3)throw Error('Left terrain '+JSON.stringify({frame,index,pos:v.position.toArray()}));if(Math.sqrt(d)>15)throw Error('Route deviation '+JSON.stringify({frame,index,error:Math.sqrt(d),pos:v.position.toArray()}));
 }throw Error('Route timeout '+JSON.stringify({index,pos:v.position.toArray(),speed:v.speed}));}
test('Complete boulevard drive around every district',()=>{const r=follow(nav.roads[0].samples);fs.writeFileSync('reports/v2-driven-route.json',JSON.stringify(r.path));assert(r.maxError<3.8,JSON.stringify({...r,path:undefined}));return {...r,path:undefined};});
test('Complete independent race lap',()=>{const r=follow(nav.track,{speed:6});assert(r.maxError<3.2,JSON.stringify({...r,path:undefined}));return {...r,path:undefined};});
test('Loop physically reaches the top and exits',()=>{const first=vec(nav.loop.points[0]);reset(first.clone().add(new THREE.Vector3(-5,1.2,0)));v.chassis.physical.body.setLinvel({x:19,y:0,z:0},true);v.input.accelerating=1;v.input.boosting=1;const before=loop.completed;let maxHeight=0;for(let i=0;i<300;i++){step();maxHeight=Math.max(maxHeight,v.position.y);if(loop.completed>before)break;}const contact=loop.contactSamples.filter(n=>n>=2).length/Math.max(1,loop.contactSamples.length);assert(loop.completed>before,JSON.stringify({index:loop.index,position:v.position.toArray(),maxHeight}));assert(maxHeight>18);assert(contact>.6,'contact '+contact);return {completed:loop.completed,maxHeight,contact};});
test('Continuous district tour, loop branch and return to Central Plaza',()=>{
 physics.resetProps();const tour=follow(nav.roads[0].samples);const ringToBranch=follow(nav.roads[0].samples.slice(0,81),{resetStart:false});
 const approach=follow(nav.roads[2].samples,{resetStart:false,speed:8,enterLoop:true});const before=loop.completed;v.input.accelerating=1;v.input.boosting=1;v.input.steering=0;v.input.braking=0;
 for(let i=0;i<300&&loop.completed===before;i++)step();assert(loop.completed>before,'Loop not entered from the connected road '+JSON.stringify({position:v.position.toArray(),index:loop.index,active:loop.active}));
 const exit=follow(nav.roads[3].samples,{resetStart:false,speed:6});const home=follow(nav.roads[0].samples.slice(0,49).reverse(),{resetStart:false,speed:6});
 const data={districts:['Central Plaza','Projects','Achievements','Ferris Wheel','Ice Rink','Bowling','Cookies','Race area','Loop','Central Plaza'],frames:tour.frames+ringToBranch.frames+approach.frames+exit.frames+home.frames,segmentErrors:{tour:tour.maxError,toBranch:ringToBranch.maxError,approach:approach.maxError,exit:exit.maxError,home:home.maxError},maxWaypointDistance:Math.max(tour.maxError,ringToBranch.maxError,approach.maxError,exit.maxError,home.maxError),finish:v.position.toArray(),loopCompletions:loop.completed-before};
 assert(v.position.distanceTo(vec(nav.spawn))<7,JSON.stringify(data));fs.writeFileSync('reports/v2-full-tour.json',JSON.stringify({...data,path:[...tour.path,...ringToBranch.path,...approach.path,...exit.path,...home.path]},null,2));return data;
});
fs.writeFileSync('reports/v2-physics-tests.json',JSON.stringify(results,null,2));physics.world.free();if(results.some(x=>!x.passed))process.exitCode=1;
