import fs from 'node:fs';import assert from 'node:assert/strict';import * as THREE from 'three';
import {updatePrefabTerrain} from '../preview/prefab-terrain.js';
import {readGLB} from './read_glb.mjs';import {Physics,RAPIER} from '../preview/runtime/physics.js';import {Events} from '../preview/runtime/Events.js';import {PhysicsVehicle} from '../preview/runtime/PhysicsVehicle.js';import {tuneVehicle} from '../preview/runtime/driving.js';import {World2Catalog} from '../preview/world2-catalog.js';import {World2Instance} from '../preview/world2-gameplay.js';import {Bin} from '../preview/portfolio/world/core/Disposal.js';import {Tweens} from '../preview/portfolio/world/core/Tween.js';import {Achievements} from '../preview/portfolio/world2/interactions/Achievements.js';import {paintLand} from '../preview/land-builder.js';
// Canvas is inert in this headless test: geometry, state machines and Rapier are real.
// Visual correctness is checked separately in the browser.
const context=new Proxy({measureText:t=>({width:String(t).length*14}),createLinearGradient:()=>({addColorStop(){}}),createRadialGradient:()=>({addColorStop(){}})}, {get:(o,k)=>o[k]??(()=>{})});
globalThis.document={createElement:tag=>({width:512,height:512,getContext:()=>context,style:{},addEventListener(){},removeEventListener(){}})};globalThis.window={location:{origin:'http://127.0.0.1:8844'},open(){}};globalThis.localStorage={getItem:()=>null,setItem(){}};
await RAPIER.init();const world=readGLB('assets/environment/portfolio/models/world.glb').scene,vegetation=readGLB('assets/environment/portfolio/models/vegetation.glb').scene;
const data=JSON.parse(fs.readFileSync('assets/environment/portfolio/interactions.json')),manifest=JSON.parse(fs.readFileSync('assets/environment/portfolio/world-manifest.json'));const catalog=new World2Catalog(world,vegetation,data,manifest);
const results=[];function test(name,fn){try{const data=fn();results.push({name,passed:true,data});console.log('PASS',name,JSON.stringify(data));}catch(e){results.push({name,passed:false,error:e.stack});console.error('FAIL',name,e.stack);}}
function fixture(id,{yaw=0,scale=1}={}){
 const physics=new Physics(),scene=new THREE.Scene(),ticker={events:new Events(),elapsed:0,delta:1/60,deltaScaled:1/30,scale:2,alpha:1};physics.ticker=ticker;
 physics.add({type:'fixed',colliders:[{shape:'cuboid',parameters:[400,.5,400]}],position:{x:0,y:-.5,z:0}});
 const bin=new Bin(),inputs={events:new Events(),mode:'keyboard',gamepad:{type:'xbox',events:new Events()},actions:new Map(),setFilters(v){this.filters=v;},isActive(){return false;}};
 const v=new PhysicsVehicle(physics,ticker,bin,{x:200,y:2,z:200});tuneVehicle(v);const player={events:new Events(),position:v.position,state:'default',setState(s){this.state=s;},respawn(){},distanceDriven:0,boosting:0};
 const view={focusPoint:{position:v.position},kick(){},startCinematic(){this.mode='cinematic';},endCinematic(){this.mode='default';}};
 const driving={bin,ticker,tweens:new Tweens(ticker,bin),inputs,player,vehicle:v,view,audio:{play(){},impact(){},environment(){}},publishGameplay(){}};
 const manager={catalog,physics,scene,driving,ui:{},status:{area:id},reset(){this.instance?.reset();},achievements:new Achievements(driving,{node(){return null;}},bin)};
 const asset=catalog.template(catalog.byId.get(id));asset.position.set(80,0,60);asset.rotation.y=yaw;asset.scale.setScalar(scale);scene.add(asset);
 const instance=new World2Instance(manager,asset);manager.instance=instance;
 ticker.events.on('fixed',()=>physics.step(),3);
 const step=(n=1)=>{for(let i=0;i<n;i++){ticker.elapsed+=1/60;ticker.events.trigger('fixed');ticker.events.trigger('tick');}};
 const at=p=>{v.moveTo(instance.physics.point(p),0);step();};
 return {physics,scene,ticker,manager,asset,instance,player,v,step,at,done(){instance.dispose();bin.dispose();physics.destroy();}};
}
test('All World2 areas and authored physical collections available',()=>{for(const name of ['bowling','circuit','projects','toilet','achievements','behindTheScene','social','career','landing','cookie','lab','altar','timeMachine'])assert(catalog.byId.has(name),name);const physicals=[];world.traverse(o=>{if(o.userData.w2Role==='physical')physicals.push(o);});assert(catalog.entries.length>100);fs.writeFileSync('reports/v3/catalog.json',JSON.stringify(catalog.entries.map(({id,label,category,feature,size})=>({id,label,category,feature,size})),null,2));return {entries:catalog.entries.length,physicalSourceObjects:physicals.length,activities:catalog.entries.filter(x=>x.category==='World2 · actividades').length};});
test('Rotated bowling: ten real pins, ball, kinematic bumpers and reset',()=>{const f=fixture('bowling',{yaw:Math.PI/2}),b=f.instance.parts.bowling;assert.equal(b.pins.length,10);assert(b.ball);const home=b.pins[0].physical.current.position.clone();f.step(60);b.toggleBumpers();f.step(60);assert(b.bumpers.out);for(const pin of b.pins)pin.physical.body.setRotation(new THREE.Quaternion().setFromAxisAngle(new THREE.Vector3(1,0,0),Math.PI/2),true);f.step(2);assert(b.strike);assert(f.manager.achievements.groups.get('strike').unlocked);b.reset();f.step(20);assert.equal(b.pins.filter(x=>x.down).length,0);const value={pins:10,strike:true,bumpers:true,rotation:90};f.done();return value;});
test('Circuit: source gates, countdown, complete lap record and exit',()=>{const f=fixture('circuit',{yaw:.4}),c=f.instance.parts.circuit;assert.equal(c.gates.length,data.checkpoints.length);c.restart();assert.equal(f.player.state,'locked');f.step(150);assert.equal(c.state,'running');assert.equal(f.player.state,'default');for(let i=0;i<c.gates.length+1&&c.state==='running';i++)f.at(c.gates[c.targetIndex].position.clone().add(new THREE.Vector3(0,1.3,0)));assert.equal(c.records.length,1);assert(f.manager.achievements.groups.get('firstRace').unlocked);f.step(60);assert.equal(c.state,'pending');c.restart();c.exit(true);f.step(60);assert.equal(c.state,'pending');const value={checkpoints:c.gates.length,state:c.state,completedLap:true,records:c.records.length};f.done();return value;});
test('Projects: source content, cinematic, navigation and close',()=>{const f=fixture('projects',{yaw:-.7}),p=f.instance.parts.projects;p.open();assert.equal(f.player.state,'locked');f.step(45);const id=p.current.id;p.step(1);assert.notEqual(p.current.id,id);p.close();f.step(45);assert.equal(f.player.state,'default');const value={first:id,next:p.current.id};f.done();return value;});
test('Career: chronological source data and three rising lanes',()=>{const f=fixture('career',{yaw:1.1}),c=f.instance.parts.career;assert(c.lines.length>=6);assert.equal(Object.keys(c.lanes).length,4);const line=c.lines[0];f.at(line.origin.clone().add(new THREE.Vector3(0,1,0)));f.step(60);assert(c.lines.some(x=>x.isIn));assert(c.lines.some(x=>x.elevation>0));const value={stops:c.lines.length,lanes:Object.keys(c.lanes)};f.done();return value;});
test('Title: Alejandro Newport physical glyphs and knock-over reset',()=>{const f=fixture('landing'),t=f.instance.parts.title;assert.equal(t.letters.length,16);assert.equal(t.letters.map(x=>x.char).join('').toUpperCase(),'ALEJANDRONEWPORT');t.letters[0].physical.body.setRotation(new THREE.Quaternion().setFromAxisAngle(new THREE.Vector3(1,0,0),Math.PI/2),true);f.step(2);assert(t.standing<16);t.reset();assert.equal(t.standing,16);f.done();return {letters:16};});
test('Places and social modules preserve original references and prompts',()=>{const counts={};for(const id of ['toilet','achievements','behindTheScene','social','cookie','lab','altar','timeMachine']){const f=fixture(id);f.step(2);counts[id]={bodies:f.physics.physicals.length,prompts:f.instance.prompts.items.map(x=>x.label)};if(id==='social')assert(f.instance.parts.social.links.length>=4);if(id==='behindTheScene')assert(f.instance.parts.places.sceneBoard);if(id==='toilet')assert(f.instance.references.physical('refCabinPhysicalDynamic'));if(id==='cookie')assert(f.instance.parts.places.cookieSpawn);f.done();}return counts;});
test('New sea land stitches tile edges, is drivable and can be erased',()=>{const root=new THREE.Group(),editor={root,isVisible:o=>o.visible,register:o=>{o.userData.added=true;return o;}};paintLand(editor,new THREE.Vector3(16,0,8),12,1);assert(root.children.length>1);const shared=new Map();for(const tile of root.children){const p=tile.geometry.attributes.position;for(let i=0;i<p.count;i++){const key=p.getX(i)+','+p.getZ(i);if(shared.has(key))assert.equal(p.getY(i),shared.get(key));shared.set(key,p.getY(i));}}
 const physics=new Physics();physics.scene=root;root.children.forEach(o=>physics.mesh(o));physics.step();assert(Math.abs(physics.groundAt(16,8)-1)<.02);paintLand(editor,new THREE.Vector3(16,0,8),12,1,true);const a=root.children.flatMap(o=>{const p=o.geometry.attributes.position;return Array.from({length:p.count},(_,i)=>[p.getX(i),p.getY(i),p.getZ(i)]);}).find(p=>p[0]===16&&p[2]===8);assert.equal(a[1],-4);physics.destroy();return {tiles:root.children.length,watertight:true,colliderHeight:1,erasedHeight:a[1]};});
test('Behind-the-scenes hole cuts the physical floor and follows move/delete',()=>{
 const root=new THREE.Group(),ground=new THREE.Mesh(new THREE.PlaneGeometry(50,50,50,50).rotateX(-Math.PI/2),new THREE.MeshBasicMaterial());ground.userData={terrain:true,collision:true};root.add(ground);const original=ground.geometry.index.count;
 const pit=new THREE.Group();pit.userData={world2Asset:'behindTheScene',world2Pit:{centre:[0,0,0],radius:6.5}};root.add(pit);updatePrefabTerrain(root,true);const pa=ground.geometry.attributes.position,ix=ground.geometry.index.array;let area=0;for(let i=0;i<ix.length;i+=3){const a=ix[i],b=ix[i+1],c=ix[i+2];area+=Math.abs((pa.getX(b)-pa.getX(a))*(pa.getZ(c)-pa.getZ(a))-(pa.getZ(b)-pa.getZ(a))*(pa.getX(c)-pa.getX(a)))/2;}assert(area<2500-120&&area>2500-145,'Exact contour removes the circular floor area');
 const probe=()=>{const p=new Physics();p.mesh(ground);p.step();return p;};let p=probe();assert.equal(p.groundAt(0,0),null);assert(Math.abs(p.groundAt(15,0))<.01);p.destroy();pit.position.x=15;updatePrefabTerrain(root);p=probe();assert.equal(p.groundAt(15,0),null);assert(Math.abs(p.groundAt(0,0))<.01);p.destroy();pit.visible=false;updatePrefabTerrain(root);assert.equal(ground.geometry.index.count,original);return {cut:true,collisionFollowsMove:true,restoredAfterDelete:true};
});
test('Two bowling copies share the world but preserve independent bodies and resets',()=>{
 const f=fixture('bowling'),asset=catalog.template(catalog.byId.get('bowling'));asset.position.set(-80,0,-60);asset.rotation.y=.7;f.scene.add(asset);const second=new World2Instance(f.manager,asset),a=f.instance.parts.bowling,b=second.parts.bowling;
 assert.equal(a.pins.length+b.pins.length,20);assert.notEqual(a.pins[0].physical.raw,b.pins[0].physical.raw);f.step(10);const before=b.pins[0].physical.body.translation().clone();a.reset();assert(b.pins[0].physical.body.translation().distanceTo(before)<1e-5);second.dispose();f.done();return {pins:20,independentReset:true};
});
fs.writeFileSync('reports/v3/functional-tests.json',JSON.stringify(results,null,2));if(results.some(x=>!x.passed))process.exitCode=1;
