import fs from 'node:fs';
import assert from 'node:assert/strict';
import * as THREE from 'three';
import {AssetDefinitions,cloneAsset,tagAssetParts,applyMaterialPreset,applyPhysicsPreset,collectRuntimeEdits} from '../preview/asset-definitions.js';
import {WorldEditor} from '../preview/editor.js';
import {readGLB} from './read_glb.mjs';
import {Physics,RAPIER} from '../preview/runtime/physics.js';
import {World2Catalog} from '../preview/world2-catalog.js';
import {World2Instance,authoringPreview,simulationDriver} from '../preview/world2-gameplay.js';
import {Achievements} from '../preview/portfolio/world2/interactions/Achievements.js';

const results=[];async function test(name,fn){try{const evidence=await fn();results.push({name,passed:true,evidence});console.log('PASS',name,JSON.stringify(evidence));}catch(error){results.push({name,passed:false,error:error.stack});console.error('FAIL',name,error);}}
const source=new THREE.Group();source.name='Pine';const trunk=new THREE.Mesh(new THREE.CylinderGeometry(.3,.5,3,8),new THREE.MeshStandardMaterial({color:0x704d36}));trunk.name='Trunk';trunk.position.y=1.5;trunk.userData.collision=true;source.add(trunk);const crown=new THREE.Mesh(new THREE.ConeGeometry(2,4,8),new THREE.MeshStandardMaterial({color:0x468957}));crown.name='Crown';crown.position.y=4;source.add(crown);
const store=new AssetDefinitions();const base=store.add({id:'test-pine',label:'Pine',category:'Nature',node:source});
await test('Every definition has independent metadata and stable editable parts',()=>{for(const field of ['id','name','category','version','source','dimensions','pivot','defaultMaterial','physicsPreset','collisionPreset','tags','thumbnail','editableChildren'])assert(field in base,field);assert.equal(base.editableChildren,3);const a=store.instantiate(base.id),b=store.instantiate(base.id);assert.equal(a.children[0].geometry,b.children[0].geometry);assert.equal(a.children[1].userData.assetPartId,b.children[1].userData.assetPartId);return {sharedGeometry:true,stableParts:3};});
await test('Isolated child transform/material edit leaves source untouched until Save',()=>{const edit=store.edit(base.id),child=edit.getObjectByName('Crown');child.position.y=6;applyMaterialPreset(child,'Ice');assert.equal(base.node.getObjectByName('Crown').position.y,4);assert.equal(base.node.getObjectByName('Crown').material.color.getHex(),0x468957);store.save(base.id,edit);const next=store.instantiate(base.id);assert.equal(next.getObjectByName('Crown').position.y,6);assert.equal(next.getObjectByName('Crown').material.color.getHex(),0x9fdce6);return {childHeight:6,color:'#9fdce6',version:store.get(base.id).version};});
await test('Source propagation retains existing instance position, rotation and scale',()=>{const world=new THREE.Group(),a=store.instantiate(base.id),b=store.instantiate(base.id);a.userData.aw_id='a';b.userData.aw_id='b';a.position.set(12,2,-8);a.rotation.set(.1,.7,.2);a.scale.set(1.4,1.8,.9);b.position.set(-30,0,44);world.add(a,b);const p=a.position.toArray(),q=a.quaternion.toArray(),s=a.scale.toArray();const edit=store.edit(base.id);edit.getObjectByName('Trunk').scale.y=1.5;store.save(base.id,edit);const editor={root:world,assetDefinitions:store,registry:new Map(),baseline:new Map(),reindexInstance:WorldEditor.prototype.reindexInstance,replaceAssetInstance:WorldEditor.prototype.replaceAssetInstance};WorldEditor.prototype.refreshDefinitionInstances.call(editor);assert.deepEqual(a.position.toArray(),p);assert.deepEqual(a.quaternion.toArray(),q);assert.deepEqual(a.scale.toArray(),s);assert.equal(a.getObjectByName('Trunk').scale.y,1.5);assert.equal(b.getObjectByName('Trunk').scale.y,1.5);return {propagated:2,transformsUnchanged:true};});
await test('Save As New and Edit Instance remain independent of the original',()=>{const variant=store.saveAs(base.id,store.edit(base.id),'Pine Snow');assert.notEqual(variant.id,base.id);const world=new THREE.Group(),copy=store.instantiate(base.id);copy.userData.assetInstanceOverride=true;copy.getObjectByName('Crown').visible=false;world.add(copy);const edit=store.edit(base.id);edit.getObjectByName('Trunk').position.y=10;store.save(base.id,edit);WorldEditor.prototype.refreshDefinitionInstances.call({root:world,assetDefinitions:store,replaceAssetInstance(){throw Error('Instance override was replaced');}});assert.equal(variant.node.getObjectByName('Trunk').position.y,1.5);assert.equal(copy.getObjectByName('Crown').visible,false);assert(store.get(base.id));assert(store.get(variant.id));return {variantId:variant.id,sourcePreserved:true,instancePreserved:true};});
await test('Hierarchy parent/unparent, rename, lock, hide, duplicate and delete survive persistence',async()=>{const edit=store.edit(base.id),a=edit.getObjectByName('Trunk'),b=edit.getObjectByName('Crown');a.name='Stem';a.userData.assetLocked=true;b.visible=false;edit.updateMatrixWorld(true);const before=b.getWorldPosition(new THREE.Vector3());a.attach(b);assert(b.getWorldPosition(new THREE.Vector3()).distanceTo(before)<1e-6);edit.attach(b);const duplicate=cloneAsset(a,true);duplicate.name='Stem Copy';duplicate.userData.assetPartId='copy';edit.add(duplicate);b.removeFromParent();applyPhysicsPreset(duplicate,'Medium Dynamic');store.save(base.id,edit);const restored=new AssetDefinitions();await restored.restore(store.document());const output=restored.instantiate(base.id);assert(output.getObjectByName('Stem').userData.assetLocked);assert(!output.getObjectByName('Crown'));assert.equal(output.getObjectByName('Stem Copy').userData.mass,12);assert.equal(restored.definitions.size,2);return {definitions:2,hierarchyPreserved:true,physicsPreset:'Medium Dynamic'};});
await test('Base-world Edit Instance hierarchy survives real world save/restore',async()=>{const make=()=>{const root=new THREE.Group();root.userData.baseDocument='native-instance-test';root.userData.aw_id='world';const tree=cloneAsset(source);tree.userData.aw_id='native-tree';tree.userData.assetDefinitionId=base.id;tree.userData.assetDefinitionVersion=store.get(base.id).version;root.add(tree);tree.children.forEach((n,i)=>n.userData.aw_id='native-child-'+i);const editor={root,assetDefinitions:store,registry:new Map(),baseline:new Map(),notify(){},updateHistory(){},select(){},isVisible:o=>o.visible,terrainHeightAt:()=>0,reindexInstance:WorldEditor.prototype.reindexInstance,replaceAssetInstance:WorldEditor.prototype.replaceAssetInstance,capture:WorldEditor.prototype.capture,apply:WorldEditor.prototype.apply,refreshDefinitionInstances:WorldEditor.prototype.refreshDefinitionInstances};root.traverse(n=>{editor.registry.set(n.userData.aw_id,n);editor.baseline.set(n.userData.aw_id,{geometry:n.geometry,material:n.material});});return {editor,tree};};const a=make();a.tree.userData.assetInstanceOverride=true;a.tree.position.set(8,0,12);a.tree.getObjectByName('Crown').removeFromParent();a.tree.getObjectByName('Trunk').name='Only this instance';let document;const previous=globalThis.fetch;globalThis.fetch=async(url,options)=>{if(options?.method==='POST'){document=JSON.parse(options.body);return {ok:true};}return {ok:true,json:async()=>document};};try{assert(await WorldEditor.prototype.save.call(a.editor,true));assert.equal(document.instanceOverrides.length,1);const b=make();await WorldEditor.prototype.restore.call(b.editor);assert(!b.tree.getObjectByName('Crown'));assert(b.tree.getObjectByName('Only this instance'));assert.equal(b.tree.position.x,8);assert(b.tree.userData.assetInstanceOverride);return {serializedOverrides:1,removedChildStaysRemoved:true,instanceX:8};}finally{globalThis.fetch=previous;}});

// Rendering is browser-tested separately; geometry, state machines and physics are real.
const context=new Proxy({measureText:t=>({width:String(t).length*14}),createLinearGradient:()=>({addColorStop(){}}),createRadialGradient:()=>({addColorStop(){}})},{get:(o,k)=>o[k]??(()=>{})});
globalThis.document={createElement:()=>({width:512,height:512,getContext:()=>context,style:{},addEventListener(){},removeEventListener(){}})};globalThis.window={location:{origin:'http://127.0.0.1:8844'},open(){}};globalThis.localStorage={getItem:()=>null,setItem(){}};
await RAPIER.init();const catalog=new World2Catalog(readGLB('assets/environment/portfolio/models/world.glb').scene,readGLB('assets/environment/portfolio/models/vegetation.glb').scene,JSON.parse(fs.readFileSync('assets/environment/portfolio/interactions.json')),JSON.parse(fs.readFileSync('assets/environment/portfolio/world-manifest.json')));
function fixture(asset){const physics=new Physics(),scene=new THREE.Scene(),driving=simulationDriver(physics,new THREE.Vector3(10000,10000,10000));physics.ticker=driving.ticker;scene.add(asset);const manager={catalog,physics,scene,driving,status:{area:'test'},ui:{},reset(){},achievements:new Achievements({...driving,publishGameplay(){}},{node(){return null;}},driving.bin)};const instance=new World2Instance(manager,asset);return {instance,physics,driving,done(){instance.dispose();driving.dispose();physics.destroy();}};}
await test('World2 original physical child edits change visible mesh and real collider',()=>{const entry=catalog.byId.get('toilet'),asset=catalog.template(entry);asset.clear();asset.add(authoringPreview(catalog,entry));tagAssetParts(asset);let cabin;asset.traverse(n=>{if(n.userData.w2Source==='refCabinPhysicalDynamic')cabin=n;});assert(cabin);const p=cabin.getWorldPosition(new THREE.Vector3());cabin.position.x+=3;cabin.userData.assetPartEdited=true;const edited=cabin.getWorldPosition(new THREE.Vector3());const f=fixture(asset);const runtime=f.instance.references.node('refCabinPhysicalDynamic'),body=f.instance.references.physical('refCabinPhysicalDynamic');assert(runtime);assert(body);const actual=body.current.position;assert(Math.abs(actual.x-(edited.x+entry.anchor[0]))<1e-4);assert(collectRuntimeEdits(asset).length>0);f.done();return {bodyMovedMetres:edited.x-p.x,colliderMatches:true};});
await test('World2 generated name child edits persist in dynamics and reset home',()=>{const entry=catalog.byId.get('landing'),asset=catalog.template(entry);asset.clear();asset.add(authoringPreview(catalog,entry));tagAssetParts(asset);const letter=[];asset.traverse(n=>{if(n.isMesh&&n.name.startsWith('runtime:title:Mesh'))letter.push(n);});assert.equal(letter.length,16);const first=letter[0];first.position.y+=2;first.scale.setScalar(1.4);first.userData.assetPartEdited=true;first.material=first.material.clone();first.material.color.set(0xe433cc);first.userData.materialEdited=true;const expected=first.getWorldPosition(new THREE.Vector3());const f=fixture(asset),actual=f.instance.parts.title.letters[0];assert.equal(actual.mesh.material.color.getHex(),0xe433cc);actual.mesh.geometry.computeBoundingBox();const expectedHalf=actual.mesh.geometry.boundingBox.getSize(new THREE.Vector3()).multiplyScalar(.7);assert(Math.abs(actual.physical.colliders[0].halfExtents().x-expectedHalf.x)<1e-4);assert(Math.abs(actual.physical.current.position.y-expected.y)<1e-4);actual.physical.body.setTranslation({x:0,y:10,z:0},true);f.instance.parts.title.reset();assert(Math.abs(actual.physical.body.translation().y-expected.y)<1e-4);f.done();return {glyphs:16,changedColor:'#e433cc',colliderScale:1.4,resetKeepsEdit:true};});
await test('World2 original interaction modules still activate after source editing',()=>{const entry=catalog.byId.get('bowling'),asset=catalog.template(entry);asset.clear();asset.add(authoringPreview(catalog,entry));tagAssetParts(asset);let ball;asset.traverse(n=>{if(n.userData.w2Source==='refBallPhysicalDynamic')ball=n;});assert(ball);ball.position.z+=1;ball.userData.assetPartEdited=true;const f=fixture(asset),b=f.instance.parts.bowling;assert.equal(b.pins.length,10);assert(b.ball);b.toggleBumpers();assert(b.bumpers);b.reset();assert.equal(b.pins.filter(p=>p.down).length,0);f.done();return {pins:10,ball:true,bumpers:true,reset:true};});
fs.mkdirSync('reports/v4',{recursive:true});fs.writeFileSync('reports/v4/asset-studio-tests.json',JSON.stringify(results,null,2));if(results.some(r=>!r.passed))process.exitCode=1;
