import fs from 'node:fs';
import assert from 'node:assert/strict';
import * as THREE from 'three';
import {savedWorldFixture,SavedObjectLoader} from './helpers/saved-world.mjs';
import {syncCareerPreviews} from '../preview/career-frame.js';
import {cloneAsset,AssetDefinitions,replaceInstanceContent} from '../preview/asset-definitions.js';
import {WorldEditor} from '../preview/editor.js';
import {World2Instance,simulationDriver} from '../preview/world2-gameplay.js';
import {Physics} from '../preview/runtime/physics.js';
import {Achievements} from '../preview/portfolio/world2/interactions/Achievements.js';

const results=[];async function test(name,fn){try{const evidence=await fn();results.push({name,passed:true,evidence});console.log('PASS',name,JSON.stringify(evidence));}catch(error){results.push({name,passed:false,error:error.stack});console.error('FAIL',name,error);}}
const context=new Proxy({measureText:t=>({width:String(t).length*14}),createLinearGradient:()=>({addColorStop(){}}),createRadialGradient:()=>({addColorStop(){}})},{get:(o,k)=>o[k]??(()=>{})});
globalThis.HTMLCanvasElement=class{constructor(){this.width=512;this.height=512;this.style={};}getContext(){return context;}toDataURL(){return 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+a9YQAAAAASUVORK5CYII=';}addEventListener(){}removeEventListener(){}};
globalThis.document={createElement:()=>new HTMLCanvasElement()};globalThis.window={location:{origin:'http://127.0.0.1:8844'},open(){}};globalThis.localStorage={getItem:()=>null,setItem(){}};
const fixture=await savedWorldFixture(),{catalog}=fixture,original=fixture.registry.get('v4:world2:career');assert(original);
function parts(asset){let source,generated;asset.traverse(n=>{if(n.userData.w2Source==='career')source=n;if(n.userData.assetRuntimeKey==='runtime:career#0')generated=n;});assert(source&&generated);return {source,generated,strips:generated.children.slice(0,3)};}
function matrixError(a,b){return Math.max(...a.elements.map((n,i)=>Math.abs(n-b.elements[i])));}
function transforms(asset){asset.updateWorldMatrix(true,true);const rows=[];asset.traverse(n=>rows.push({id:n.userData.aw_id,name:n.name,p:n.position.toArray(),q:n.quaternion.toArray(),s:n.scale.toArray(),visible:n.visible}));return rows;}
function runtime(asset){const physics=new Physics(),scene=new THREE.Scene(),driving=simulationDriver(physics,new THREE.Vector3(10000,10000,10000));physics.ticker=driving.ticker;scene.add(asset);const manager={catalog,physics,scene,driving,status:{area:'test'},ui:{},reset(){},achievements:new Achievements({...driving,publishGameplay(){}},{node(){return null;}},driving.bin)},instance=new World2Instance(manager,asset);return {instance,driving,done(){instance.dispose();driving.dispose();physics.destroy();}};}
function editSource(asset){const {source}=parts(asset);source.name='Studies and work · edited model';source.position.add(new THREE.Vector3(4,1.2,-3));source.rotation.y=.72;source.scale.set(1.35,.85,1.15);source.userData.assetPartEdited=true;syncCareerPreviews(asset,catalog);}

await test('Actual saved Career placement and every child transform remain unchanged on load and Drive entry',()=>{
 const asset=cloneAsset(original,true),before=transforms(asset),{strips}=parts(asset),expected=strips.map(n=>n.matrixWorld.clone());syncCareerPreviews(asset,catalog);assert.deepEqual(transforms(asset),before);const f=runtime(asset);try{const actual=f.instance.parts.career.group.children.slice(0,3);actual.forEach((n,i)=>assert(matrixError(n.matrixWorld,expected[i])<1e-6));return {savedPosition:asset.position.toArray(),savedScale:asset.scale.toArray(),stripsAlignedOnFirstFrame:3,childTransformsPreserved:before.length};}finally{f.done();assert.deepEqual(transforms(asset),before);}
});
await test('Moving rotating and scaling the internal model carries all generated Career parts together',()=>{
 const asset=cloneAsset(original,true),{source,generated}=parts(asset);asset.updateWorldMatrix(true,true);const oldSource=source.matrixWorld.clone(),children=generated.children.map(n=>[n,n.matrixWorld.clone()]);editSource(asset);const delta=source.matrixWorld.clone().multiply(oldSource.invert());let maximumError=0;for(const [node,before]of children){const error=matrixError(node.matrixWorld,delta.clone().multiply(before));maximumError=Math.max(maximumError,error);assert(error<1e-6);}const once=transforms(asset);for(let i=0;i<10;i++)syncCareerPreviews(asset,catalog);assert.deepEqual(transforms(asset),once);return {generatedChildren:children.length,maximumMatrixError:maximumError,nonuniformScale:true,repeatSyncNoDrift:true};
});
await test('Edited source definition save reload and propagation preserve instance placement and Drive alignment',()=>{
 const store=new AssetDefinitions();store.add({id:'world2:career',label:'Career',category:'World2',node:original});const edited=store.edit('world2:career');editSource(edited);store.save('world2:career',edited);const document=JSON.parse(JSON.stringify(store.document())),loader=new SavedObjectLoader(),saved=document.definitions[0],definition={...saved,node:loader.parse(saved.object)},asset=cloneAsset(original,true),placement={p:asset.position.toArray(),q:asset.quaternion.toArray(),s:asset.scale.toArray()};replaceInstanceContent(asset,definition);syncCareerPreviews(asset,catalog);assert.deepEqual(asset.position.toArray(),placement.p);assert.deepEqual(asset.quaternion.toArray(),placement.q);assert.deepEqual(asset.scale.toArray(),placement.s);const {strips}=parts(asset);asset.updateWorldMatrix(true,true);const expected=strips.map(n=>n.matrixWorld.clone()),f=runtime(asset);try{const c=f.instance.parts.career;f.instance.frame.updateMatrixWorld(true);c.group.children.slice(0,3).forEach((n,i)=>assert(matrixError(n.matrixWorld,expected[i])<1e-6));const local=new THREE.Vector3(c.lanes.education,0,c.near-1).applyMatrix4(c.sourceFrame.inverse.clone().invert());f.driving.player.position.copy(f.instance.physics.point(local));f.driving.ticker.events.trigger('tick');assert(c.lines[0].isIn);assert(c.lines[0].elevation>0);const stoneLocal=c.lines[0].stone.getWorldPosition(new THREE.Vector3()).applyMatrix4(c.group.matrixWorld.clone().invert());assert(Math.abs(stoneLocal.x-c.lanes.education)<1e-6);assert.equal(c.visited.size>0,true);return {definitionVersion:saved.version,placementPreserved:true,firstTickActivatesEducation:true,stoneLaneError:Math.abs(stoneLocal.x-c.lanes.education),stripsAligned:3};}finally{f.done();}
});
await test('Edited instance JSON save reload and stop/apply keep model and luminous lines in the same frame',()=>{
 const asset=cloneAsset(original,true);editSource(asset);asset.userData.assetInstanceOverride=true;const saved=JSON.parse(JSON.stringify(asset.toJSON())),restored=new SavedObjectLoader().parse(saved);syncCareerPreviews(restored,catalog);const root=new THREE.Group();root.add(restored);const editor={root,catalog,registry:new Map(),baseline:new Map(),select(){},updateHistory(){},terrainHeightAt:()=>0};root.traverse(n=>{editor.registry.set(n.userData.aw_id,n);editor.baseline.set(n.userData.aw_id,{geometry:n.geometry,material:n.material});});const before=transforms(restored),state=WorldEditor.prototype.capture.call(editor),expected=parts(restored).strips.map(n=>n.matrixWorld.clone()),f=runtime(restored);try{const c=f.instance.parts.career;c.group.children.slice(0,3).forEach((n,i)=>assert(matrixError(n.matrixWorld,expected[i])<1e-6));const point=c.centre.clone().applyMatrix4(c.sourceFrame.inverse.clone().invert());f.driving.player.position.copy(f.instance.physics.point(point));for(let i=0;i<30;i++)f.driving.ticker.events.trigger('tick');}finally{f.done();root.add(restored);}WorldEditor.prototype.apply.call(editor,state);assert.deepEqual(transforms(restored),before);return {instanceOverride:true,serializationPreserved:true,stopRestoresEveryTransform:true,frames:30};
});
fs.mkdirSync('reports/v4',{recursive:true});fs.writeFileSync('reports/v4/career-frame-tests.json',JSON.stringify({passed:results.every(r=>r.passed),results},null,2));if(results.some(r=>!r.passed))process.exitCode=1;
