import fs from 'node:fs';
import assert from 'node:assert/strict';
import * as THREE from 'three';
import {SceneLightBudget} from '../preview/runtime/scene-lights.js';

const results=[];function test(name,fn){try{const evidence=fn();results.push({name,passed:true,evidence});console.log('PASS',name,JSON.stringify(evidence));}catch(error){results.push({name,passed:false,error:error.stack});console.error('FAIL',name,error);}}
function fixture(){const scene=new THREE.Scene(),root=new THREE.Group(),camera=new THREE.PerspectiveCamera();scene.add(root);for(let i=0;i<256;i++){const light=new THREE.PointLight(0xffcd88,1+i/256,8,2);light.name='Lamp '+i;light.position.set(i*3,2,0);light.visible=i%2===0;light.userData.nightReady=true;root.add(light);}const beacon=new THREE.SpotLight(0xffdf9d,15,90,.13,.6,1);beacon.position.set(0,20,0);beacon.target.position.set(20,20,0);beacon.visible=false;beacon.userData.nightReady=true;root.add(beacon,beacon.target);const budget=new SceneLightBudget(scene,root),focus=new THREE.Vector3();return {scene,root,camera,budget,focus,beacon};}
function renderedLights(scene,camera){const lights=[];scene.traverseVisible(n=>{if((n.isPointLight||n.isSpotLight)&&n.layers.test(camera.layers))lights.push(n);});return lights;}
test('257 authored lights use exactly nine stable render slots and zero local daylight lights',()=>{
 const f=fixture(),{root,camera,budget,focus}=f,states=root.children.filter(n=>n.isLight).map(n=>[n,n.visible,n.layers.mask,JSON.stringify(n.userData)]);let seen=[];const renderer={render:scene=>{seen=renderedLights(scene,camera);}};
 budget.render(renderer,camera,true,focus,0);assert.equal(seen.filter(n=>n.isPointLight).length,8);assert.equal(seen.filter(n=>n.isSpotLight).length,1);assert(seen.every(n=>!n.castShadow));const ids=seen.map(n=>n.uuid);
 for(let i=1;i<=5;i++){focus.x=i*130;budget.render(renderer,camera,true,focus,i*600);assert.deepEqual(seen.map(n=>n.uuid),ids);assert.equal(seen.length,9);}
 budget.render(renderer,camera,false,focus,3600);assert.equal(seen.length,0);for(const [n,v,mask,data]of states){assert.equal(n.visible,v);assert.equal(n.layers.mask,mask);assert.equal(JSON.stringify(n.userData),data);}assert(!JSON.stringify(root.toJSON()).includes('Runtime nearby lights'));budget.dispose();assert.equal(f.scene.children.length,1);return {authoredLights:257,nightSlots:9,daySlots:0,stablePool:true,sourceStateUnchanged:true};
});
test('Nearby selection is throttled, weighted by explicit priority and respects authored hiding',()=>{
 const {root,camera,budget,focus}=fixture(),renderer={render(){}};budget.render(renderer,camera,true,focus,0);assert.deepEqual(budget.slots.filter(s=>s.kind==='point').map(s=>s.source.name),Array.from({length:8},(_,i)=>'Lamp '+i));
 focus.x=600;budget.render(renderer,camera,true,focus,100);assert.equal(budget.slots[0].source.name,'Lamp 0');budget.render(renderer,camera,true,focus,500);assert.equal(budget.slots[0].source.name,'Lamp 200');const priority=root.getObjectByName('Lamp 0');priority.userData.lightPriority=1e8;const hidden=root.getObjectByName('Lamp 200');hidden.visible=false;hidden.userData.assetVisibilityEdited=true;budget.invalidate();budget.render(renderer,camera,true,focus,501);assert.equal(budget.slots[0].source,priority);assert(!budget.slots.some(s=>s.source===hidden));const parent=new THREE.Group();root.add(parent);parent.add(priority);parent.visible=false;budget.invalidate();budget.render(renderer,camera,true,focus,502);assert(!budget.slots.some(s=>s.source===priority));budget.dispose();return {refreshIntervalMs:500,priorityHonored:true,hiddenLightAndAncestorExcluded:true};
});
test('Animated beacon and edited lamp properties update each frame without rebuilding the pool',()=>{
 const {root,camera,budget,focus,beacon}=fixture(),renderer={render(){}};budget.render(renderer,camera,true,focus,0);const slot=budget.slots.find(s=>s.kind==='spot').light,id=slot.uuid;beacon.position.set(4,9,-2);beacon.target.position.set(-30,9,14);beacon.intensity=7;beacon.angle=.2;beacon.penumbra=.3;beacon.color.set('#e248bf');const lamp=root.getObjectByName('Lamp 0');lamp.intensity=3;lamp.distance=12;budget.render(renderer,camera,true,focus,16);assert.equal(slot.uuid,id);assert(slot.position.equals(beacon.position));assert(slot.target.position.equals(beacon.target.position));assert.equal(slot.intensity,7);assert.equal(slot.angle,.2);assert(slot.color.equals(beacon.color));assert.equal(budget.slots[0].light.intensity,3);assert.equal(budget.slots[0].light.distance,12);lamp.visible=false;lamp.userData.assetVisibilityEdited=true;budget.render(renderer,camera,true,focus,32);assert.equal(budget.slots[0].light.intensity,0);budget.dispose();return {animatedPoseLive:true,editedIntensityLive:true,hiddenImmediately:true};
});
test('Render failures restore every authored light layer and leave serialization unchanged',()=>{
 const {root,camera,budget,focus}=fixture(),lamp=root.getObjectByName('Lamp 0');lamp.layers.enable(3);const masks=root.children.filter(n=>n.isLight).map(n=>[n,n.layers.mask]);assert.throws(()=>budget.render({render(){assert(masks.every(([n])=>n.layers.mask===0));throw new Error('context lost');}},camera,true,focus,0),/context lost/);for(const [n,mask]of masks)assert.equal(n.layers.mask,mask);assert.equal(lamp.layers.mask,9);budget.dispose();return {restoredAfterException:true,nondefaultLayerPreserved:true};
});
fs.mkdirSync('reports/v4',{recursive:true});fs.writeFileSync('reports/v4/light-budget-tests.json',JSON.stringify({passed:results.every(r=>r.passed),results},null,2));if(results.some(r=>!r.passed))process.exitCode=1;
