import fs from 'node:fs';import assert from 'node:assert/strict';import * as THREE from 'three';
import {worldFixture} from './helpers/world-v4.mjs';import {Physics} from '../preview/runtime/physics.js';import {PhysicsVehicle} from '../preview/runtime/PhysicsVehicle.js';import {Events} from '../preview/runtime/Events.js';import {LoopAssist} from '../preview/runtime/loop.js';import {tuneVehicle} from '../preview/runtime/driving.js';import {roadGeometryData} from '../preview/roads/road-system.js';import {planarBoolean} from '../preview/roads/planar.js';import {updatePrefabTerrain} from '../preview/prefab-terrain.js';import {validateWorld} from '../preview/world-validation.js';
const f=await worldFixture(),root=f.root;updatePrefabTerrain(root,true);const results=[];function test(name,fn){try{const data=fn();results.push({name,passed:true,data});console.log('PASS',name,JSON.stringify(data));}catch(e){results.push({name,passed:false,error:e.stack});console.error('FAIL',name,e.stack);}}
const physics=new Physics();physics.scene=root;root.updateMatrixWorld(true);const visible=o=>{for(let p=o;p;p=p.parent)if(!p.visible||p.userData.deleted)return false;return true;},ancestor=(o,key)=>{for(let p=o;p;p=p.parent)if(p.userData[key])return true;return false;};const nodes=[];root.traverse(o=>{if(!visible(o)||!o.userData.collision||ancestor(o,'world2Asset'))return;let owner=false;for(let p=o.parent;p&&p!==root;p=p.parent)if(p.userData.collision)owner=true;if(!owner)nodes.push(o);});nodes.forEach(o=>physics.mesh(o));
test('Every persistent map object has a unique stable instance path',()=>{const ids=new Set();root.traverse(o=>{if(o.userData.proceduralDerived)return;assert(o.userData.aw_id,o.name);assert(!ids.has(o.userData.aw_id),o.userData.aw_id+' '+o.name);ids.add(o.userData.aw_id);});return {objects:ids.size};});
test('All regular roads form one connected graph and the race course stays separate',()=>{const roads=f.roads.filter(o=>o.userData.road_network!=='race'),adj=roads.map(()=>[]);for(let i=0;i<roads.length;i++)for(let j=i+1;j<roads.length;j++){const a=roadGeometryData(roads[i]),b=roadGeometryData(roads[j]);if(a.bounds.maxX<b.bounds.minX||b.bounds.maxX<a.bounds.minX||a.bounds.maxZ<b.bounds.minZ||b.bounds.maxZ<a.bounds.minZ)continue;const inter=planarBoolean([a.polys,b.polys],c=>c[0]>0&&c[1]>0);if(inter.area>.01){adj[i].push(j);adj[j].push(i);}}const reached=new Set([0]),queue=[0];while(queue.length){const n=queue.shift();for(const v of adj[n])if(!reached.has(v)){reached.add(v);queue.push(v);}}assert.equal(reached.size,roads.length,JSON.stringify(roads.map((o,i)=>({name:o.name,links:adj[i].map(j=>roads[j].name)}))));const race=f.roads.find(o=>o.userData.road_network==='race');for(const road of roads){const a=roadGeometryData(road),b=roadGeometryData(race),inter=planarBoolean([a.polys,b.polys],c=>c[0]>0&&c[1]>0);assert(inter.area<.01,road.name+' overlaps F1');}return {roads:roads.length,connected:reached.size,raceSeparate:true};});
test('Loop road endpoints and tangents match the actual translated stunt',()=>{const start=f.navigation.loop.points[0],end=f.navigation.loop.points.at(-1),a=roadGeometryData(f.roads.find(o=>o.name==='Fairground Approach')),b=roadGeometryData(f.roads.find(o=>o.name==='Loop Approach')),point=p=>new THREE.Vector3(p[0],p[2],-p[1]);assert(a.samples.at(-1).p.distanceTo(point(start))<1e-6);assert(b.samples[0].p.distanceTo(point(end))<1e-6);assert(a.samples.at(-1).t.x>.98);assert(b.samples[0].t.x>.98);return {start,end,inTangent:a.samples.at(-1).t.toArray(),outTangent:b.samples[0].t.toArray()};});
test('Actual loop completes from its connected approach with wheel contact and a clean exit',()=>{const ticker={events:new Events(),elapsed:0,deltaScaled:1/30,scale:2};physics.ticker=ticker;const first=f.navigation.loop.points[0],v=new PhysicsVehicle(physics,ticker,{add(){}},{x:first[0]-7,y:first[2]+1.2,z:-first[1]});tuneVehicle(v);const loop=new LoopAssist(v,f.navigation.loop.points);ticker.events.on('fixed',()=>loop.beforeStep(),1);ticker.events.on('fixed',()=>physics.step(),3);const step=()=>{ticker.elapsed+=1/60;ticker.events.trigger('fixed');};for(let i=0;i<60;i++)step();v.chassis.physical.body.setLinvel({x:19,y:0,z:0},true);v.input.accelerating=1;v.input.boosting=1;let maxHeight=v.position.y,path=[];for(let i=0;i<330;i++){step();maxHeight=Math.max(maxHeight,v.position.y);if(i%3===0)path.push(v.position.toArray());if(loop.completed)break;}const contact=loop.contactSamples.filter(n=>n>=2).length/Math.max(1,loop.contactSamples.length);assert(loop.completed>=1,JSON.stringify({position:v.position.toArray(),index:loop.index,maxHeight}));assert(maxHeight>18);assert(contact>.6,'wheel contact '+contact);fs.writeFileSync('reports/v4/loop-route.json',JSON.stringify(path));return {completed:loop.completed,maxHeight,contact,finish:v.position.toArray()};});
test('Marina spine physically reaches all three finger docks',()=>{physics.step();const ys=[];for(const x of [11,27,43]){const y=physics.groundAt(x,88);assert(y>.18,JSON.stringify({x,y}));ys.push(y);}return {x:[11,27,43],deckHeights:ys};});
test('Actual Corsair is parked on the aviation apron with no duplicate vehicle collider',()=>{const plane=root.children.find(o=>o.userData.assetDefinitionId==='vehicle-corsair'),pad=root.getObjectByName('Aircraft parking apron');assert(plane&&pad);assert(plane.userData.worldZone===23);const b=new THREE.Box3().setFromObject(plane),p=new THREE.Box3().setFromObject(pad);assert(Math.abs(b.min.y-p.max.y-.005)<1e-5);assert(b.min.x>=p.min.x&&b.max.x<=p.max.x&&b.min.z>=p.min.z&&b.max.z<=p.max.z);let vertices=0;plane.traverse(o=>{assert.equal(o.userData.collision,false);vertices+=o.geometry?.attributes.position?.count||0;});assert(vertices>10000,'Must contain source aircraft geometry');return {sourceVertices:vertices,size:b.getSize(new THREE.Vector3()).toArray(),parkedBottom:b.min.y,padTop:p.max.y};});
test('Native map roads have no default self intersections or attraction conflicts',()=>{const report=validateWorld(root,{definitions:new Map(f.library.map(x=>[x.id,x])),spawn:[41,1.35,1],beachRegion:{minX:-95,maxX:-20,minZ:91,maxZ:127}});fs.writeFileSync('reports/v4/map-validation.json',JSON.stringify(report,null,2));assert.deepEqual(report.issues,[]);return {summary:report.summary,issues:report.issues};});
physics.destroy();fs.writeFileSync('reports/v4/routes-tests.json',JSON.stringify(results,null,2));if(results.some(x=>!x.passed))process.exitCode=1;
