import fs from 'node:fs';
import assert from 'node:assert/strict';
import {spawnSync} from 'node:child_process';
import * as THREE from 'three';
import {createRoad,createJunction,rebuildRoad,rebuildRoadNetwork,definitionFromObject,roadGeometryData,roadDiagnostics,createRoadDebug,smoothRoad,migrateLegacyRoads} from '../preview/roads/road-system.js';
import {planarBoolean,rectangle,disc,cellsArea} from '../preview/roads/planar.js';
import {Physics,RAPIER} from '../preview/runtime/physics.js';
const results=[];const test=async(name,fn)=>{const start=performance.now();try{const data=await fn();results.push({name,passed:true,ms:performance.now()-start,data});console.log('PASS',name,JSON.stringify(data));}catch(e){results.push({name,passed:false,error:e.stack});console.error('FAIL',name,e.stack);}};
function oracle(polygons,triangles){const py=spawnSync('python3',['-c',`import json,sys
sys.path.insert(0,'scripts/vendor')
from shapely.geometry import Polygon
from shapely.ops import unary_union
x=json.load(sys.stdin)
p=unary_union([Polygon(a) for a in x['polygons'] if len(a)>2])
t=[Polygon(a) for a in x['triangles'] if len(a)>2]
u=unary_union(t)
print(json.dumps({'expected':p.area,'actual':u.area,'sum':sum(a.area for a in t),'symmetricDifference':p.symmetric_difference(u).area,'valid':u.is_valid}))`],{input:JSON.stringify({polygons,triangles}),encoding:'utf8',maxBuffer:8*1024*1024});if(py.status!==0)throw Error(py.stderr);return JSON.parse(py.stdout);}
function triangles(o){o.updateWorldMatrix(true,true);const p=o.geometry.attributes.position,idx=o.geometry.index?.array||Array.from({length:p.count},(_,i)=>i),a=[];for(let i=0;i<idx.length;i+=3)a.push([idx[i],idx[i+1],idx[i+2]].map(j=>{const v=new THREE.Vector3().fromBufferAttribute(p,j).applyMatrix4(o.matrixWorld);return [v.x,v.z];}));return a;}
const mark=o=>o.children.find(n=>n.userData.roadPart==='Lane and edge markings');
const curb=o=>o.children.find(n=>n.userData.roadPart==='Distance-pattern race curbs');
await test('Straight road has exact width, flat caps, distance UV and upward normals',()=>{const o=createRoad({points:[[-20,.2,0],[0,.2,0],[20,.2,0]],width:7});assert(Math.abs(o.userData.roadStats.area-280)<1e-6);const g=o.geometry,p=g.attributes.position,uv=g.attributes.uv;for(let i=0;i<p.count;i++){assert(Math.abs(uv.getX(i)-(p.getX(i)+20)/4)<2e-6);assert(g.attributes.normal.getY(i)>.999);}assert.equal(mark(o).userData.collision,false);return {area:280,length:40,uvMetresPerRepeat:4};});
await test('Editing a road point regenerates lane/edge marks, rails and asphalt together',()=>{const o=createRoad({points:[[-16,.2,0],[0,.2,0],[16,.2,0]],width:7,rails:{left:true,right:true}});const before=mark(o).geometry.attributes.position.array.slice(),old=o.geometry;const p=definitionFromObject(o).points;p[1][2]=12;o.userData.road_points=JSON.stringify(p);rebuildRoad(o);assert.notEqual(o.geometry,old);assert.notDeepEqual(mark(o).geometry.attributes.position.array,before);assert(o.children.filter(n=>n.userData.roadPart?.includes('guardrail')).length===2);const m=mark(o).geometry.attributes.position;assert(Array.from({length:m.count},(_,i)=>m.getZ(i)).some(z=>z>10));return {updatedSurface:true,updatedMarkings:true,rails:2};});
await test('Race curbs are coupled and pattern repeats by metres, preserved in portable texture',()=>{const o=createRoad({points:[[-15,.2,-10],[15,.2,-10],[15,.2,10],[-15,.2,10]],closed:true,width:6,type:'race',grid:true});const gridBefore=o.children.find(n=>n.userData.roadPart==='Curve-bound starting grid').geometry.attributes.position.array.slice();const first=curb(o),old=first.geometry.attributes.position.array.slice();assert.equal(first.material.map.image.width,2);assert.equal(first.material.map.wrapS,THREE.RepeatWrapping);assert.equal(first.material.map.magFilter,THREE.NearestFilter);const p=definitionFromObject(o).points;p[1][0]+=9;o.userData.road_points=JSON.stringify(p);rebuildRoad(o);assert.notDeepEqual(curb(o).geometry.attributes.position.array,old);assert(curb(o).geometry.attributes.uv.count>20);assert.notDeepEqual(o.children.find(n=>n.userData.roadPart==='Curve-bound starting grid').geometry.attributes.position.array,gridBefore);for(const part of [o,...o.children])if(part.geometry?.attributes.position)for(const attr of Object.values(part.geometry.attributes))assert.equal(attr.count,part.geometry.attributes.position.count);return {gridUpdated:true,curbUpdated:true,stripeLength:2,textureWidth:2};});
await test('Boolean surface matches independent GEOS union for tight turns, crossings and holes',()=>{const fixtures=[{id:'hairpin',points:[[-20,.2,0],[0,.2,0],[1,.2,2],[-20,.2,3]],width:8},{id:'crossing',points:[[-20,.2,-20],[20,.2,20],[-20,.2,20],[20,.2,-20]],width:7},{id:'closed loop',points:[[-15,.2,-10],[15,.2,-10],[15,.2,10],[-15,.2,10]],closed:true,width:6}];const out=[];for(const f of fixtures){const o=createRoad(f),data=roadGeometryData(o),r=oracle(data.polys,triangles(o));assert(r.valid);assert(r.symmetricDifference<.002,JSON.stringify(r));assert(Math.abs(r.sum-r.actual)<.002,'triangle interiors overlap');if(f.id!=='closed loop')assert(o.userData.roadDiagnostics.some(x=>x.code.includes('SELF_INTERSECTION')));out.push({name:f.id,...r,warnings:o.userData.roadDiagnostics.length});}return out;});
await test('Junction network resolves coincident asphalt to one nonoverlapping surface',()=>{const root=createJunction('Crossroad',{width:7,length:20}),roads=root.children.filter(o=>o.userData.road);const polys=roads.flatMap(o=>roadGeometryData(o).polys),tris=roads.flatMap(triangles),r=oracle(polys,tris);assert(Math.abs(r.expected-511)<.0001);assert(r.symmetricDifference<.002);assert(Math.abs(r.sum-r.actual)<.002);return r;});
await test('All junction presets generate coherent editable master curves',()=>{const counts={};for(const kind of ['T Junction','Crossroad','Roundabout','Merge','Split']){const root=createJunction(kind),roads=root.children.filter(o=>o.userData.road_points);assert(roads.length>=2);assert(roads.every(o=>o.userData.roadStats.area>0));if(kind==='Roundabout'){const road=roads[0],data=roadGeometryData(road),inside=planarBoolean([data.polys,[rectangle([-.1,0],[.1,0],.2)]],c=>c[0]>0&&c[1]>0);assert(inside.area<1e-6);}counts[kind]=roads.length;}return counts;});
await test('Conform to terrain and road collision share identical current geometry',async()=>{await RAPIER.init();const heightAt=(x,z)=>.15+.015*x,root=new THREE.Group(),o=createRoad({points:[[-20,.205,0],[0,.205,0],[20,.205,0]],width:7,conformToTerrain:true},{heightAt});root.add(o);rebuildRoadNetwork(root,{heightAt});const physics=new Physics();physics.scene=root;const physical=physics.mesh(o);physics.step();assert.equal(physical.colliders.length,1,'paint must not become a physical road');for(const x of [-15,0,15])assert(Math.abs(physics.groundAt(x,0)-(heightAt(x,0)+.055))<.001);physics.destroy();return {heightSamples:3,colliders:1,paintExcluded:true};});
await test('A bridge owns its deck surface and moving it restores the road and collider',async()=>{await RAPIER.init();const root=new THREE.Group(),o=createRoad({points:[[-10,.205,0],[0,.205,0],[10,.205,0]],width:7}),bridge=new THREE.Group(),deck=new THREE.Mesh(new THREE.BoxGeometry(22,.2,9));bridge.userData.drivableBridge=true;deck.name='Deck';deck.position.y=.105;bridge.add(deck);root.add(o,bridge);rebuildRoadNetwork(root);assert.equal(o.geometry.index.count,0);assert.equal(o.userData.collision,false);const physics=new Physics();physics.scene=root;assert.equal(physics.mesh(o),undefined);bridge.position.x=30;rebuildRoadNetwork(root);assert.equal(o.userData.collision,true);assert(Math.abs(o.userData.roadStats.area-140)<1e-6);const physical=physics.mesh(o);physics.step();assert.equal(physical.colliders.length,1);assert(Math.abs(physics.groundAt(0,0)-.205)<.001);physics.destroy();return {coveredArea:0,restoredArea:140,restoredCollider:true};});
await test('Transform, source serialization and rebuilt instance preserve shape alignment',()=>{const root=new THREE.Group(),o=createRoad({points:[[-15,.2,0],[0,.2,4],[15,.2,0]],width:7});o.position.set(33,.4,-12);o.rotation.y=.63;root.add(o);rebuildRoadNetwork(root);const data=JSON.stringify(o.toJSON()),copy=new THREE.ObjectLoader().parse(JSON.parse(data)),root2=new THREE.Group();root2.add(copy);rebuildRoadNetwork(root2);assert(copy.position.distanceTo(o.position)<1e-8);assert(Math.abs(copy.userData.roadStats.area-o.userData.roadStats.area)<1e-6);assert.equal(copy.children.length,o.children.length);return {area:copy.userData.roadStats.area,children:copy.children.length};});
await test('Auto smooth, obstacle/water warnings and separate debug geometry work',()=>{const root=new THREE.Group(),o=createRoad({points:[[-20,.2,0],[0,.2,0],[1,.2,2],[-20,.2,3]],width:8});root.add(o);const before=definitionFromObject(o).points.length;smoothRoad(o);rebuildRoad(o);assert(definitionFromObject(o).points.length>before);const building=new THREE.Mesh(new THREE.BoxGeometry(4,5,4));building.position.set(-10,2,0);root.add(building);const issues=roadDiagnostics(root,{obstacles:[building],seaLevel:.4});assert(issues.some(x=>x.code==='ROAD_ATTRACTION_COLLISION'));assert(issues.some(x=>x.code==='WATER_LEVEL_ISSUES'));const debug=createRoadDebug(root);assert(debug.userData.editorOnly);assert(!root.children.includes(debug));return {warnings:issues.map(x=>x.code),debugObjects:debug.children.length};});
await test('Removing a road restores its neighbour and unchanged networks reuse geometry',()=>{const root=createJunction('Crossroad',{width:7,length:20}),[a,b]=root.children;const old=a.geometry;rebuildRoadNetwork(root);assert.equal(a.geometry,old);b.visible=false;rebuildRoadNetwork(root);assert(Math.abs(a.userData.roadStats.area-280)<.0001);b.visible=true;rebuildRoadNetwork(root);assert(Math.abs(a.userData.roadStats.area+b.userData.roadStats.area-511)<.0001);return {stableCache:true,visibilityRebuild:true};});
await test('Legacy standalone road decorations retire without affecting other props',()=>{const root=new THREE.Group(),o=createRoad({points:[[-10,.2,0],[0,.2,0],[10,.2,0]],width:7},{name:'Island Boulevard'});root.add(o);for(const name of ['Island Boulevard edge.001','Boulevard centre dash.002','Race kerb.004','Garden bench']){const n=new THREE.Mesh(new THREE.BoxGeometry(1,1,1));n.name=name;root.add(n);}const r=migrateLegacyRoads(root);assert.equal(r.retired.length,3);assert(root.getObjectByName('Garden bench').visible);return r;});
fs.mkdirSync('reports/v4',{recursive:true});fs.writeFileSync('reports/v4/roads-tests.json',JSON.stringify(results,null,2));if(results.some(r=>!r.passed))process.exitCode=1;
