import fs from 'node:fs';
import assert from 'node:assert/strict';
import * as THREE from 'three';
import {TrackGameplay,createTrackFurniture} from '../preview/track-gameplay.js';
import {createRoad,sampleRoad} from '../preview/roads/road-system.js';
import {ROAD_PLANS} from '../preview/world-map.js';
import {Physics,RAPIER,collisionMeshes} from '../preview/runtime/physics.js';
import {PhysicsVehicle} from '../preview/runtime/PhysicsVehicle.js';
import {tuneVehicle} from '../preview/runtime/driving.js';
import {Events} from '../preview/runtime/Events.js';
import {Bin} from '../preview/portfolio/world/core/Disposal.js';
import {Tweens} from '../preview/portfolio/world/core/Tween.js';
import {Circuit} from '../preview/portfolio/world2/interactions/Circuit.js';

// Canvas drawing is inert here; controller, transforms and Rapier are real.
const context=new Proxy({measureText:t=>({width:String(t).length*14})},{get:(o,k)=>o[k]??(()=>{})});
globalThis.document={createElement:()=>({width:512,height:512,getContext:()=>context,style:{},addEventListener(){},removeEventListener(){}})};
const storage=new Map([['helloworld-world2-circuit-v1',JSON.stringify({records:[{time:9,at:1}]})]]);globalThis.localStorage={getItem:k=>storage.get(k)??null,setItem:(k,v)=>storage.set(k,v)};
await RAPIER.init();const results=[];
function test(name,fn){try{const evidence=fn();results.push({name,passed:true,evidence});console.log('PASS',name,JSON.stringify(evidence));}catch(error){results.push({name,passed:false,error:error.stack});console.error('FAIL',name,error);}}
function fixture(){const scene=new THREE.Scene(),root=new THREE.Group();scene.add(root);const plan=ROAD_PLANS.find(p=>p[4]==='race');const road=createRoad({id:'test-catalunya',points:plan[1].map(([x,n])=>[x,.205,-n]),width:plan[2],closed:true,type:'race'});root.add(road);const furniture=createTrackFurniture(root),physics=new Physics();physics.scene=root;physics.add({type:'fixed',position:{x:0,y:-.5,z:0},colliders:[{shape:'cuboid',parameters:[400,.5,400]}]});physics.mesh(road);
 const ticker={events:new Events(),elapsed:0,delta:1/60,deltaScaled:1/30,scale:2,alpha:1},bin=new Bin();physics.ticker=ticker;const inputs={events:new Events(),mode:'keyboard',gamepad:{type:'xbox',events:new Events()},actions:new Map(),setFilters(){},isActive(){return false;}};
 const vehicle=new PhysicsVehicle(physics,ticker,bin,{x:200,y:2,z:200});tuneVehicle(vehicle);const player={events:new Events(),position:vehicle.position,state:'default',setState(s){this.state=s;},respawn(){}};const unlocked=new Set(),achievements={unlock:id=>unlocked.add(id)};let resets=0;
 const driving={ticker,bin,inputs,vehicle,player,tweens:new Tweens(ticker,bin),audio:{play(){}},publishGameplay(){}};ticker.events.on('fixed',()=>physics.step(),3);const initialListeners=ticker.events.count(),initialObjects=scene.children.length,initialBodies=physics.world.bodies.len();
 const make=()=>new TrackGameplay({root,scene,physics,driving,achievements,onReset:()=>resets++});let track=make();
 const step=(n=1)=>{for(let i=0;i<n;i++){ticker.elapsed+=1/60;ticker.events.trigger('fixed');ticker.events.trigger('tick');}};
 const at=p=>{vehicle.moveTo(p,0);step();};return {scene,root,road,furniture,physics,ticker,bin,driving,vehicle,player,unlocked,track,make,step,at,initialListeners,initialObjects,initialBodies,get resets(){return resets;},done(){track.dispose();bin.dispose();physics.destroy();}};
}
test('Editable race furniture follows current curve and instance transforms without accumulating offsets',()=>{const f=fixture();try{const {road,furniture,track}=f;assert(track.circuit instanceof Circuit);assert.equal(track.circuit.gates.length,12);assert.equal(track.circuit.update,Circuit.prototype.update);assert.equal(track.circuit.restart,Circuit.prototype.restart);assert.equal(track.circuit.records.length,0);const current=furniture.gantry.position.clone();createTrackFurniture(f.root);assert(furniture.gantry.position.distanceTo(current)<1e-8);furniture.board.position.y+=.3;const old=furniture.board.position.clone();createTrackFurniture(f.root);assert(furniture.board.position.distanceTo(old)<1e-8);f.track.dispose();road.position.set(18,2,-7);road.rotation.y=.54;road.scale.setScalar(1.3);const d=road.userData.roadDefinition;d.points[0][0]-=4;road.userData.road_points=JSON.stringify(d.points);createTrackFurniture(f.root);const next=f.make();const expected=furniture.curve.getPointAt(.04);const live=sampleRoad(d).curve;const gate=live.getPointAt(.04).applyMatrix4(road.matrixWorld);assert(next.circuit.gates[0].position.distanceTo(gate)<1e-6);assert(Math.abs(next.circuit.gates[0].a.distanceTo(next.circuit.gates[0].b)-d.width*1.3)<1e-6);next.dispose();return {checkpoints:12,widthAfterScale:d.width*1.3,curveEditsFollow:true,sourceControllerUnchanged:true};}finally{f.done();}});
test('Native Catalunya proximity prompt starts the original three-beat countdown and timed checkpoint sequence',()=>{const f=fixture();try{const c=f.track.circuit,start=f.track.references.position('refInteractivePoint.003');f.at(start.clone().add(new THREE.Vector3(0,1.4,0)));f.step(30);assert.equal(f.track.hud().prompt,'Start Catalunya race');assert(f.track.interact());assert.equal(f.player.state,'locked');assert.equal(c.state,'countdown');assert.equal(f.track.hud().headline,'3');f.step(100);assert.equal(c.state,'running');assert.equal(f.player.state,'default');assert(f.track.hud().timer);assert(f.resets===1);for(let i=0;i<c.gates.length+1&&c.state==='running';i++)f.at(c.gates[c.targetIndex].position.clone().add(new THREE.Vector3(0,1.4,0)));assert.equal(c.records.length,1);assert(f.unlocked.has('firstRace'));assert.equal(c.state,'ending');const time=c.records[0].time;assert(time>0);const key=f.track.references.storageKey;assert(key.startsWith('helloworld-v4-catalunya-laps-'));assert.equal(JSON.parse(storage.get('helloworld-world2-circuit-v1')).records[0].time,9);f.step(45);assert.equal(c.state,'pending');return {gates:12,lapTime:time,recordKey:key,legacyRecordsUntouched:true,firstRaceAchievement:true};}finally{f.done();}});
test('Lap records reload, respawn uses last gate, forced exit adds no record and record reset persists',()=>{const f=fixture();try{const c=f.track.circuit;assert(c.records.length>=1);const count=c.records.length;c.restart();f.step(100);f.at(c.gates[0].position.clone().add(new THREE.Vector3(0,1.3,0)));assert(c.lastGate);assert(f.track.respawn());assert(f.vehicle.position.distanceTo(c.lastGate.respawn)<1e-5);c.exit(true);f.step(40);assert.equal(c.records.length,count);assert.equal(c.state,'pending');c.clearRecords();assert.equal(JSON.parse(storage.get(f.track.references.storageKey)).records.length,0);return {recordsReloaded:count,checkpointRespawn:true,forcedExitNoRecord:true,clearSaved:true};}finally{f.done();}});
test('Gantry leaves the racing lane clear and repeated dispose restores authored materials with no callbacks or bodies leaked',()=>{const f=fixture();try{const {gantry}=f.furniture;for(const m of collisionMeshes(gantry)){m.geometry.computeBoundingBox();const box=m.geometry.boundingBox.clone().applyMatrix4(m.matrix);assert(box.min.y>3.8||box.max.x< -f.furniture.definition.width/2||box.min.x>f.furniture.definition.width/2,'Gantry collider blocks driving lane: '+m.name);}f.track.circuit.restart();f.step(100);f.track.circuit.exit(true);f.track.dispose();assert.equal(f.ticker.events.count(),f.initialListeners);assert.equal(f.scene.children.length,f.initialObjects);assert.equal(f.physics.world.bodies.len(),f.initialBodies);const lamp=gantry.getObjectByName('refStartingLights'),home=lamp.position.clone(),material=lamp.material;for(let i=0;i<3;i++){const t=f.make();t.circuit.restart();t.dispose();assert(lamp.position.distanceTo(home)<1e-9);assert.equal(lamp.material,material);}f.step(90);assert.equal(f.ticker.events.count(),f.initialListeners);assert.equal(f.player.state,'default');return {reentries:3,pendingCallbacksRemoved:true,authoredMaterialRestored:true,bodyCount:f.initialBodies};}finally{f.done();}});
test('Renamed or removed editable screen parts keep the remaining native activity usable',()=>{const f=fixture();try{f.track.dispose();const light=f.furniture.gantry.getObjectByName('refStartingLights');light.name='Custom edited lamp plate';const board=f.furniture.board.getObjectByName('refLeaderboard');board.removeFromParent();f.road.userData.road_width=8;createTrackFurniture(f.root);const t=f.make();assert.equal(t.circuit.lights,light);assert.equal(t.circuit.board.group.visible,false);assert(f.furniture.gantry.getObjectByName('Gantry footing 1').position.x>4.9);t.circuit.restart();f.step(100);assert.equal(t.circuit.state,'running');t.dispose();return {stableReferencesAfterRename:true,removedBoardRespected:true,widerGantryClearance:true};}finally{f.done();}});
test('Deleted track safely disables only the native race controller',()=>{const scene=new THREE.Scene(),root=new THREE.Group();scene.add(root);const track=new TrackGameplay({root,scene,physics:null,driving:{}});assert.equal(track.circuit,null);assert.equal(track.busy,false);assert.equal(track.interact(),false);track.dispose();return {emptyTrackSafe:true};});
fs.mkdirSync('reports/v4',{recursive:true});fs.writeFileSync('reports/v4/track-tests.json',JSON.stringify(results,null,2));if(results.some(r=>!r.passed))process.exitCode=1;
