import assert from 'node:assert/strict';
import fs from 'node:fs';
import * as THREE from 'three';
import {Physics,RAPIER} from '../preview/runtime/physics.js';
import {PhysicsVehicle} from '../preview/runtime/PhysicsVehicle.js';
import {tuneVehicle} from '../preview/runtime/driving.js';
import {VehicleInput} from '../preview/runtime/vehicle-input.js';
import {VehicleModes,VehicleWater} from '../preview/runtime/vehicle-mode.js';
import {Player} from '../preview/portfolio/world/player/Player.js';
import {ACTION_DEFINITIONS} from '../preview/portfolio/world/input/Inputs.js';
import {Events} from '../preview/runtime/Events.js';
import {Tweens} from '../preview/portfolio/world/core/Tween.js';
import {readGLB} from './read_glb.mjs';
import {VisualVehicle} from '../preview/runtime/VisualVehicle.js';
import {playerCarTemplate} from '../preview/runtime/vehicle-assets.js';
import {Materials} from '../preview/runtime/materials.js';
import {preparePlaneModel} from '../preview/runtime/plane-visual.js';
import {Bin} from '../preview/portfolio/world/core/Disposal.js';
await RAPIER.init();
const results=[];
async function test(name,fn){try{const data=await fn();results.push({name,passed:true,data});console.log('PASS',name,JSON.stringify(data));}catch(error){results.push({name,passed:false,error:error.stack});console.error('FAIL',name,error.stack);}}
function fixture({angle=0,ice=false,terrain=null,spawn=new THREE.Vector3(0,1.3,0),parking=true}={}){
 const physics=new Physics(),ticker={events:new Events(),delta:1/60,deltaScaled:1/30,elapsed:0,scale:2,alpha:1};physics.ticker=ticker;physics.waterElevation=-.35;
 if(terrain)physics.add({type:'fixed',category:'floor',colliders:[{shape:'trimesh',parameters:terrain}],metadata:{ground_surface:true,surface_type:'sand'}});
 else physics.add({type:'fixed',category:'floor',position:{x:0,y:-.5,z:0},rotation:new THREE.Quaternion().setFromAxisAngle(new THREE.Vector3(0,0,1),angle),colliders:[{shape:'cuboid',parameters:[1000,.5,1000]}],metadata:{ground_surface:true,surface_type:ice?'ice':'road'}});
 const bin={add(){}},inputs={events:new Events(),actions:new Map(ACTION_DEFINITIONS.map(a=>[a.name,{...a,active:false,value:0}])),keyboard:{events:new Events(),pressed:new Set()},gamepad:{joysticks:{left:{active:false},right:{active:false}}},pointer:{isDown:false},isActive(name){return this.actions.get(name)?.active??false;},setFilters(){}};
 const v=new PhysicsVehicle(physics,ticker,bin,spawn);tuneVehicle(v);v.parking.enabled=parking;
 const view={camera:new THREE.PerspectiveCamera(25,1,.1,1000),focusPoint:{position:new THREE.Vector3(),trackedPosition:new THREE.Vector3()},snapToTarget(){},endCinematic(){},kick(){}};
 const respawns={getDefault:()=>({position:spawn.clone(),rotation:0}),getClosest:()=>({position:spawn.clone(),rotation:0})};
 const player=new Player(inputs,v,view,respawns,ticker,new Tweens(ticker,bin),null,bin);
 let modes;const manager=new VehicleInput(inputs,()=>modes.toggle(),()=>ticker.elapsed*1000);modes=new VehicleModes(v,player,view,physics,ticker,manager,{seaLevel:-.35});
 let recoveries=0;const water=new VehicleWater(physics,v,{seaLevel:-.35,onRecover:()=>recoveries++});ticker.events.on('fixed',()=>physics.step(),3);
 const action=(name,on)=>{const a=inputs.actions.get(name);a.active=on;a.value=+on;inputs.events.trigger(name,[a]);};
 const step=(n=1)=>{for(let i=0;i<n;i++){ticker.elapsed+=1/60;ticker.events.trigger('fixed');water.update(1/60,modes.isPlane);}};
 const key=(code,on)=>{on?inputs.keyboard.pressed.add(code):inputs.keyboard.pressed.delete(code);inputs.keyboard.events.trigger(on?'down':'up',[code,code]);};
 return {physics,ticker,inputs,v,view,player,manager,modes,water,step,key,action,get recoveries(){return recoveries;},done(){manager.dispose();modes.dispose();physics.destroy();}};
}
await test('SPACE buffer: a single tap brakes, double tap transforms without brake, held key does not repeat',()=>{
 const f=fixture();f.step(90);f.key('Space',true);f.step(2);f.key('Space',false);f.step(10);assert.equal(f.v.input.braking,0);f.key('Space',true);assert.equal(f.modes.mode,'PLANE');assert.equal(f.v.input.braking,0);f.key('Space',false);f.step(30);f.key('Space',true);f.step(2);f.key('Space',false);f.step(10);f.key('Space',true);f.key('Space',false);assert.equal(f.modes.mode,'CAR');f.step(30);
 f.key('Space',true);f.step(2);f.key('Space',false);f.step(18);assert.equal(f.v.input.braking,1);assert.equal(f.modes.mode,'CAR');f.step(20);assert.equal(f.v.input.braking,0);
 f.key('Space',true);f.step(25);assert.equal(f.v.input.braking,1);f.key('Space',true);assert.equal(f.modes.mode,'CAR');f.key('Space',false);f.step(12);assert.equal(f.v.input.braking,0);f.done();return {doubleWindowMs:300,singleBrake:true,noPrematureDoubleBrake:true};
});
await test('Creep diagnosis and parking: flat and 0.57° terrain stable, hill rolls, throttle releases immediately',()=>{
 const runs=[];for(const [angle,parking] of [[0,false],[.01,false],[.01,true],[.12,true]]){const f=fixture({angle,parking});f.step(300);const start=f.v.position.clone();f.step(1500);const distance=f.v.position.distanceTo(start);runs.push({degrees:angle*180/Math.PI,parking,distance,throttle:f.v.input.accelerating});if(angle===.01&&parking){assert(distance<.00001);assert(f.v.parking.active);f.action('forward',true);f.step(30);assert(f.v.xzSpeed>2);assert(!f.v.parking.active);}f.done();}assert(runs[0].distance<1e-6);assert(runs[1].distance>.2);assert(runs[3].distance>2);return runs;
});
await test('Rotated parked headings have no amplified yaw jitter or drift',()=>{const runs=[];for(const yaw of [.3,.8,1.57,2.1,2.75]){const f=fixture();f.v.moveTo({x:0,y:1.3,z:0},yaw);f.step(300);const start=f.v.position.clone(),orientation=f.v.quaternion.clone().normalize();let yawTravel=0,previous=orientation.clone();for(let i=0;i<1200;i++){f.step();yawTravel+=previous.angleTo(f.v.quaternion.clone().normalize());previous.copy(f.v.quaternion).normalize();}assert(f.v.parking.active);assert(f.v.position.distanceTo(start)<.001,JSON.stringify({yaw,start:start.toArray(),end:f.v.position.toArray()}));assert(yawTravel<.001,JSON.stringify({yaw,yawTravel,angular:f.v.chassis.physical.body.angvel()}));runs.push({yaw,yawTravel,distance:f.v.position.distanceTo(start)});f.done();}return runs;});
await test('Source physics retained: wheel positions, COM, chassis colliders and driving force',()=>{const f=fixture();f.step(90);const before=f.v.position.clone(),body=f.v.chassis.physical.body;f.action('forward',true);f.step(60);assert(f.v.position.x-before.x>8);assert.equal(body.numColliders(),3);assert.equal(f.v.controller.numWheels(),4);assert(Math.abs(body.localCom().y+.9)<.001);assert.equal(f.v.boostMultiplier,.6);assert.equal(f.v.wheels.items[0].basePosition.x,.9);const data={distance:f.v.position.distanceTo(before),mass:body.mass(),COM:body.localCom(),wheels:4,colliders:3};f.done();return data;});
await test('Arcade flight circles an island footprint, auto-levels and respects soft ceiling',()=>{
 const f=fixture();f.step(90);f.modes.toggle();f.inputs.keyboard.pressed.add('KeyQ');f.step(130);f.inputs.keyboard.pressed.delete('KeyQ');f.step(90);const altitude=f.v.position.y;assert(altitude>15);f.manager.flight=()=>({throttle:0,turn:.12,pitch:0});
 const path=[],start=f.v.position.clone(),initialHeading=f.modes.heading;let minX=Infinity,maxX=-Infinity,minZ=Infinity,maxZ=-Infinity;
 for(let i=0;i<2455;i++){f.step();minX=Math.min(minX,f.v.position.x);maxX=Math.max(maxX,f.v.position.x);minZ=Math.min(minZ,f.v.position.z);maxZ=Math.max(maxZ,f.v.position.z);if(i%30===0)path.push(f.v.position.toArray());}
 assert(maxX-minX>245&&maxZ-minZ>245);assert(Math.abs(f.modes.heading-initialHeading)>6);assert(Math.abs(f.v.position.y-altitude)<1);assert(f.v.position.distanceTo(start)<20);
 f.manager.flight=()=>({throttle:1,turn:0,pitch:1});f.step(1800);assert(f.v.position.y<86);assert(f.v.position.y>78);assert(Number.isFinite(f.view.camera.position.x));fs.writeFileSync('reports/v4/flight-route.json',JSON.stringify(path));const data={width:maxX-minX,depth:maxZ-minZ,startAltitude:altitude,maxClimbAltitude:f.v.position.y,samples:path.length};f.done();return data;
});
await test('Plane to car keeps the airborne position and velocity, really falls and lands; 24 repeated transformations keep one body',()=>{
 const f=fixture();f.step(90);const bodies=f.physics.world.bodies.len(),handle=f.v.chassis.physical.body.handle;f.modes.toggle();f.inputs.keyboard.pressed.add('KeyQ');f.step(180);f.inputs.keyboard.pressed.delete('KeyQ');const before=f.v.position.clone(),velocity={...f.v.chassis.physical.body.linvel()};f.modes.toggle();assert(f.v.position.distanceTo(before)<1e-6);assert.equal(f.modes.mode,'CAR');assert.equal(f.v.activeController,true);const after=f.v.chassis.physical.body.linvel();assert(Math.abs(after.x-velocity.x)<1e-6);f.step(45);assert(f.v.position.y<before.y);assert(f.v.position.y>2);let lowest=f.v.position.y;for(let i=0;i<300;i++){f.step();lowest=Math.min(lowest,f.v.position.y);}assert(f.v.wheels.inContactCount>=3);assert(lowest>0,JSON.stringify({lowest,final:f.v.position.toArray(),contacts:f.v.wheels.inContactCount}));
 for(let i=0;i<24;i++){f.modes.toggle();f.step(18);assert.equal(f.physics.world.bodies.len(),bodies);assert.equal(f.v.chassis.physical.body.handle,handle);assert.equal(f.v.activeController,!f.modes.isPlane);assert.equal(f.v.controller.numWheels(),4);}
 const data={dropHeight:before.y,landedHeight:lowest,repeatedTransitions:24,rigidBodyHandle:handle,bodyCount:bodies};f.done();return data;
});
await test('Physical beach: drive from sand into shallow water and return; deep drop eventually recovers',()=>{
 const positions=[],indices=[];const height=x=>x<0?.15:Math.max(-3,.15-x*.09);
 for(let x=-40;x<=80;x+=2)for(const z of [-30,30])positions.push(x,height(x),z);
 for(let i=0;i<60;i++){const a=i*2;indices.push(a,a+1,a+2,a+1,a+3,a+2);}
 const f=fixture({terrain:[new Float32Array(positions),new Uint32Array(indices)],spawn:new THREE.Vector3(-15,1.5,0)});f.step(90);f.action('forward',true);let maxWetness=0;for(let i=0;i<180&&f.v.position.x<16;i++){f.step();maxWetness=Math.max(maxWetness,f.water.wetness);}assert(f.v.position.x>12);assert(maxWetness>.2);assert.equal(f.recoveries,0);f.action('forward',false);f.action('backward',true);for(let i=0;i<600&&f.v.position.x> -3;i++)f.step();assert(f.v.position.x< -3,JSON.stringify({position:f.v.position.toArray(),speed:f.v.speed}));assert.equal(f.recoveries,0);const returnPosition=f.v.position.toArray();
 f.action('backward',false);f.v.moveTo({x:65,y:25,z:0});f.step(360);assert(f.recoveries>0);const data={maxWetness,returnPosition,deepDropRecoveries:f.recoveries};f.done();return data;
});
await test('User airplane is embedded and has actual multi-material low-poly geometry',()=>{const {scene,doc}=readGLB('assets/vehicles/plane/corsair.glb');let count=0;scene.traverse(o=>{if(o.isMesh)count++;});assert(count>=9);assert.equal(doc.images?.length??0,0);assert(doc.materials.length>=7);return {meshes:count,materials:doc.materials.length,bytes:fs.statSync('assets/vehicles/plane/corsair.glb').size,externalDependencies:0};});
await test('Flight collides with a major building and recovers without another rigid body',()=>{
 const f=fixture();f.physics.add({type:'fixed',category:'floor',position:{x:35,y:9,z:0},colliders:[{shape:'cuboid',parameters:[2,9,8]}]});f.step(90);let hits=0,maxForce=0;f.v.events.on('collision',force=>{maxForce=Math.max(maxForce,force);if(force>.015)hits++;});f.modes.toggle();const positions=[];for(let i=0;i<360;i++){f.step();positions.push(f.v.position.toArray());}assert(hits>0,JSON.stringify({maxForce,final:f.v.position.toArray(),near:positions.filter(p=>p[0]>29&&p[0]<40).slice(0,10)}));assert(positions.every(p=>p.every(Number.isFinite)));assert(f.v.position.distanceTo(new THREE.Vector3(35,9,0))>10);assert.equal(f.physics.world.bodies.len(),3);const data={hits,final:f.v.position.toArray(),bodyCount:3};f.done();return data;
});
await test('Ice never enters parking and released steering eases to exact zero',()=>{const f=fixture({ice:true});f.step(240);assert.equal(f.v.parking.active,false);f.action('left',true);f.step();assert.equal(f.v.input.steering,1);f.action('left',false);f.step();assert(f.v.input.steering>0&&f.v.input.steering<1);f.step(120);assert.equal(f.v.input.steering,0);assert.equal(f.v.input.accelerating,0);f.done();return {iceParking:false,smoothSteeringReturn:true,zeroThrottle:true};});
await test('Edited car definition retains part materials, suspension offsets, rotations and deletions in Drive',()=>{
 const context=new Proxy({measureText:t=>({width:String(t).length*14}),createLinearGradient:()=>({addColorStop(){}})},{get:(o,k)=>o[k]??(()=>{})});globalThis.document??={createElement:()=>({width:512,height:512,getContext:()=>context})};
 const template=playerCarTemplate();template.getObjectByName('Chassis').position.y+=.25;template.getObjectByName('Chassis').name='Renamed chassis';const roof=template.getObjectByName('Painted roof');roof.material=roof.material.clone();roof.material.color.set('#4b62dd');roof.material.metalness=.91;const wheel=template.getObjectByName('Wheel 1');wheel.position.y+=.35;wheel.rotation.z=.18;const authoredRotation=wheel.quaternion.clone();template.getObjectByName('Wheel 2').removeFromParent();template.getObjectByName('Boost cell 1').position.y=.83;const brake=template.getObjectByName('Brake lights');brake.visible=false;brake.userData.assetVisibilityEdited=true;
 const f=fixture(),bin=new Bin();const prop=f.physics.mesh(template);assert(prop&&prop.colliders.length>=6);const plane=preparePlaneModel(readGLB('assets/vehicles/plane/corsair.glb').scene);plane.position.x=30;const planeProp=f.physics.mesh(plane);assert(planeProp&&planeProp.colliders.length>=7);f.physics.remove(prop);f.physics.remove(planeProp);f.step(300);const visual=new VisualVehicle(f.v,f.player,f.inputs,f.physics,f.ticker,new Materials(bin),bin);visual.applyTemplate(template);assert(Math.abs(visual.authoredBody.position.y-.25)<1e-12);visual.camera.position.set(5,5,5);visual.camera.lookAt(0,0,0);visual.camera.updateMatrixWorld();for(let i=0;i<100;i++)visual.update();const actual=visual.chassis.getObjectByName('Painted roof');let authoredMaterialDisposed=false;actual.material.addEventListener('dispose',()=>authoredMaterialDisposed=true);assert.equal(actual.material.color.getHexString(),'4b62dd');assert.equal(actual.material.metalness,.91);assert(!visual.chassis.getObjectByName('Wheel 2'));assert(!visual.chassis.getObjectByName('Tyre 2'));assert(Math.abs(visual.wheels[0].container.position.y-(Math.min(-f.v.wheels.items[0].suspensionLength,-.5)+.35))<1e-4);assert(visual.wheels[0].container.quaternion.angleTo(authoredRotation)<1e-6);assert(Math.abs(visual.boostCells[0].position.y-.83)<1e-12);f.player.braking=1;visual.update();assert.equal(visual.brakeLights.visible,false);visual.setShell('graphite');visual.setShell('default');assert.equal(actual.material.color.getHexString(),'4b62dd');visual.setColor('#1188aa');visual.setShell('graphite');visual.setShell('default');assert.equal(actual.material.color.getHexString(),'1188aa');assert.equal(roof.material.color.getHexString(),'4b62dd');bin.dispose();assert(authoredMaterialDisposed);f.done();return {sourceMaterialPreserved:true,paintRestore:true,customWheelOffset:.35,deletedWheelAbsent:true,hiddenLightsStayHidden:true};
});
fs.mkdirSync('reports/v4',{recursive:true});fs.writeFileSync('reports/v4/vehicle-tests.json',JSON.stringify(results,null,2));if(results.some(r=>!r.passed))process.exitCode=1;
