import fs from 'node:fs';
import assert from 'node:assert/strict';
import * as THREE from 'three';
import {worldFixture} from './helpers/world-v4.mjs';
import {finishOcean} from '../preview/ocean.js';
import {waterLevelQuery} from '../preview/water-query.js';
import {worldAnimationClips} from '../preview/world-animation.js';
import {terrainHeight} from '../preview/world-map.js';
import {SEA_LEVEL,MAIN_HEIGHT} from '../preview/world-config.js';
const {root}=await worldFixture(),results=[];
function test(name,fn){try{const data=fn();results.push({name,passed:true,data});console.log('PASS',name,JSON.stringify(data));}catch(error){results.push({name,passed:false,error:error.stack});console.error('FAIL',name,error.stack);}}
test('Ocean uses actual coast depths, continuous horizon skirt and exportable vertex colours',()=>{finishOcean(root,terrainHeight);const sea=root.children.find(o=>o.userData.sea);assert.equal(sea.position.y,SEA_LEVEL);assert(sea.userData.seaDepthColors);assert.equal(sea.material.vertexColors,true);const g=sea.geometry,p=g.attributes.position,c=g.attributes.color;assert.equal(p.count,c.count);g.computeBoundingBox();assert(g.boundingBox.min.x< -1000&&g.boundingBox.max.x>1000);let min=Infinity,max=-Infinity;for(let i=0;i<c.count;i++){min=Math.min(min,c.getY(i));max=Math.max(max,c.getY(i));assert.equal(p.getY(i),0);}assert(max-min>.15);const a=new THREE.Vector3(),b=new THREE.Vector3(),d=new THREE.Vector3();for(let i=0;i<g.index.count;i+=3){a.fromBufferAttribute(p,g.index.getX(i));b.fromBufferAttribute(p,g.index.getX(i+1)).sub(a);d.fromBufferAttribute(p,g.index.getX(i+2)).sub(a);assert(b.cross(d).y>0,`inverted sea triangle ${i/3}`);}const foam=root.children.find(o=>o.userData.derivedWater);assert(foam.geometry.attributes.position.count>200);return {vertices:p.count,triangles:g.index.count/3,width:g.boundingBox.max.x-g.boundingBox.min.x,colourRange:max-min,foamSegments:foam.geometry.attributes.position.count/2};});
test('Actual water features query their authored world level; ice stays a solid surface',()=>{const query=waterLevelQuery(root,SEA_LEVEL),surfaces=[];root.traverse(o=>{if(o.userData.waterSurface)surfaces.push(o);});const values=[];for(const surface of surfaces){const p=surface.geometry.attributes.position,index=surface.geometry.index,point=new THREE.Vector3();for(let i=0;i<3;i++)point.add(new THREE.Vector3().fromBufferAttribute(p,index?index.getX(i):i));point.multiplyScalar(1/3);surface.localToWorld(point);const value=query(point.x,point.z);if(surface.userData.surface_type==='ice'){assert.equal(value,SEA_LEVEL);assert(surface.userData.collision);assert.equal(surface.userData.friction,.025);}else{assert(Math.abs(value-point.y)<.001,JSON.stringify({name:surface.parent.name,expected:point.y,value}));assert(!surface.userData.collision);}values.push({name:surface.parent.name,level:value,ice:surface.userData.surface_type==='ice'});}assert(surfaces.length>=4);assert.equal(query(800,800),SEA_LEVEL);assert(MAIN_HEIGHT-SEA_LEVEL<.65);return values;});
test('Moved, rotated and scaled lake keeps visual and water query height aligned',()=>{const lake=root.children.find(o=>o.userData.assetGenerator==='water'&&!o.userData.parameters.iceMode);assert(lake);const before={position:lake.position.clone(),rotation:lake.rotation.clone(),scale:lake.scale.clone()};lake.position.set(300,2,300);lake.rotation.y=.65;lake.scale.set(1.5,2,.8);root.updateMatrixWorld(true);const surface=lake.children.find(o=>o.userData.waterSurface),p=surface.geometry.attributes.position,index=surface.geometry.index,point=new THREE.Vector3();for(let i=0;i<3;i++)point.add(new THREE.Vector3().fromBufferAttribute(p,index?index.getX(i):i));surface.localToWorld(point.multiplyScalar(1/3));const value=waterLevelQuery(root,SEA_LEVEL)(point.x,point.z);assert(Math.abs(value-point.y)<.00001);lake.visible=false;assert.equal(waterLevelQuery(root,SEA_LEVEL)(point.x,point.z),SEA_LEVEL);lake.visible=true;lake.position.copy(before.position);lake.rotation.copy(before.rotation);lake.scale.copy(before.scale);root.updateMatrixWorld(true);return {level:value,expected:point.y,hiddenExcluded:true};});
test('All generated animation bindings resolve to actual instance nodes and survive GLTF channel mapping',()=>{const file=fs.readFileSync('exports/AlejandroWorld.glb'),doc=JSON.parse(file.subarray(20,20+file.readUInt32LE(12))),bin=file.subarray(28+file.readUInt32LE(12));function values(id){const a=doc.accessors[id],v=doc.bufferViews[a.bufferView],size={SCALAR:1,VEC3:3,VEC4:4}[a.type],result=[];assert.equal(a.componentType,5126);for(let i=0;i<a.count;i++)for(let j=0;j<size;j++)result.push(bin.readFloatLE((v.byteOffset??0)+(a.byteOffset??0)+i*(v.byteStride??size*4)+j*4));return result;}const sources=(doc.animations??[]).map(a=>new THREE.AnimationClip(a.name,-1,a.channels.map(c=>{const s=a.samplers[c.sampler],name=doc.nodes[c.target.node].name+'.'+({rotation:'quaternion',translation:'position',scale:'scale'}[c.target.path]),Track=c.target.path==='rotation'?THREE.QuaternionKeyframeTrack:THREE.VectorKeyframeTrack;return new Track(name,values(s.input),values(s.output));}))),clips=worldAnimationClips(root,sources);assert(clips.length>20);let tracks=0;const bindings=new Set();for(const clip of clips){assert(clip.duration>0);for(const track of clip.tracks){const binding=THREE.PropertyBinding.parseTrackName(track.name),node=root.getObjectByProperty('uuid',binding.nodeName);assert(node,track.name);assert(!track.name.includes('/Users/'));assert([...track.values].every(Number.isFinite));assert(['position','quaternion','scale'].includes(binding.propertyName));bindings.add(node.uuid);tracks++;}}const mixer=new THREE.AnimationMixer(root),first=clips.find(c=>c.tracks[0].name.endsWith('.quaternion')),node=root.getObjectByProperty('uuid',THREE.PropertyBinding.parseTrackName(first.tracks[0].name).nodeName),before=node.quaternion.clone();mixer.clipAction(first).play();mixer.update(.8);assert(before.angleTo(node.quaternion)>1e-5);mixer.stopAllAction();return {sourceAnimations:sources.length,clips:clips.length,tracks,animatedNodes:bindings.size};});
fs.mkdirSync('reports/v4',{recursive:true});fs.writeFileSync('reports/v4/water-animation-tests.json',JSON.stringify(results,null,2));if(results.some(r=>!r.passed))process.exitCode=1;
