import fs from 'node:fs';
import assert from 'node:assert/strict';
import * as THREE from 'three';
import {mapTerrain,authoredWorldBounds} from '../preview/world-bounds.js';
import {savedWorldFixture} from './helpers/saved-world.mjs';

const results=[];async function test(name,fn){try{const evidence=await fn();results.push({name,passed:true,evidence});console.log('PASS',name,JSON.stringify(evidence));}catch(error){results.push({name,passed:false,error:error.stack});console.error('FAIL',name,error);}}
function terrain(x0,z0,nx,nz,omit=()=>false){const positions=[],indices=[];for(let z=0;z<=nz;z++)for(let x=0;x<=nx;x++)positions.push(x0+x,.15,z0+z);for(let z=0;z<nz;z++)for(let x=0;x<nx;x++){if(omit(x,z))continue;const a=z*(nx+1)+x;indices.push(a,a+nx+1,a+1,a+1,a+nx+1,a+nx+2);}const g=new THREE.BufferGeometry();g.setAttribute('position',new THREE.Float32BufferAttribute(positions,3));g.setIndex(indices);const mesh=new THREE.Mesh(g);mesh.userData.terrain=true;return mesh;}
const area=loop=>loop.reduce((sum,p,i)=>{const next=loop[(i+1)%loop.length];return sum+p[0]*next[1]-next[0]*p[1];},0)/2;
const edges=loops=>loops.flatMap(loop=>loop.map((p,i)=>{const q=loop[(i+1)%loop.length];return Math.hypot(p[0]-q[0],p[1]-q[1]);}));
await test('Twenty thousand interior triangles collapse to one 400-edge boundary',()=>{const root=new THREE.Group();root.add(terrain(0,0,100,100));const before=performance.now(),loops=mapTerrain(root),ms=performance.now()-before;assert.equal(loops.length,1);assert.equal(loops[0].length,400);assert.equal(Math.abs(area(loops[0])),10000);assert.equal(Math.max(...edges(loops)),1);return {sourceTriangles:20000,polygons:1,boundaryPoints:400,milliseconds:ms};});
await test('Terrain holes remain separate closed loops with opposite winding',()=>{const root=new THREE.Group();root.add(terrain(0,0,10,10,(x,z)=>x>=4&&x<6&&z>=4&&z<6));const loops=mapTerrain(root);assert.equal(loops.length,2);const areas=loops.map(area);assert(areas[0]*areas[1]<0);assert.equal(Math.abs(areas.reduce((a,b)=>a+b,0)),96);assert(Math.max(...edges(loops))<=1);return {polygons:2,areas,landArea:96};});
await test('Shared tile edges weld away and touching corners do not invent long links',()=>{const root=new THREE.Group(),a=terrain(0,0,10,10),b=terrain(10,0,10,10);b.position.x=1e-7;root.add(a,b,terrain(20,10,5,5));const loops=mapTerrain(root);assert.equal(loops.length,2);assert.equal(loops.reduce((n,l)=>n+l.length,0),80);assert(Math.abs(loops.reduce((n,l)=>n+Math.abs(area(l)),0)-225)<1e-4);assert(Math.max(...edges(loops))<1.00001);return {polygons:2,boundaryPoints:80,maximumEdge:Math.max(...edges(loops))};});
await test('Sea-crossing triangles are clipped to the shoreline and hidden terrain is ignored',()=>{const g=new THREE.BufferGeometry();g.setAttribute('position',new THREE.Float32BufferAttribute([0,.65,0,2,-1.35,0,0,.65,2],3));const mesh=new THREE.Mesh(g);mesh.userData.terrain=true;const root=new THREE.Group(),hidden=terrain(-1000,-1000,10,10);hidden.visible=false;root.add(mesh,hidden);const loops=mapTerrain(root);assert.equal(loops.length,1);assert(Math.abs(Math.abs(area(loops[0]))-1.5)<1e-6);assert(loops[0].every(p=>p[0]>=0&&p[0]<=1.000001));return {polygons:1,shorelineX:Math.max(...loops[0].map(p=>p[0])),clippedArea:Math.abs(area(loops[0]))};});
await test('Migrated saved world includes southwest land without interior edges or distant closing jumps',async()=>{const {root}=await savedWorldFixture(),bounds=authoredWorldBounds(root);let triangles=0;root.traverse(n=>{if(n.userData.terrain&&n.geometry)triangles+=(n.geometry.index?.count??n.geometry.attributes.position.count)/3;});const before=performance.now(),loops=mapTerrain(root),milliseconds=performance.now()-before,points=loops.flat(),lengths=edges(loops),count=points.length,minX=Math.min(...points.map(p=>p[0])),south=Math.min(...points.map(p=>p[1]));assert(bounds.minX< -300&&bounds.maxZ>250);assert(minX< -300&&south< -250);assert(loops.length>0&&loops.length<50);assert(count<triangles/8);assert(Math.max(...lengths)<10);return {bounds,polygons:loops.length,boundaryPoints:count,sourceTriangles:triangles,maximumEdge:Math.max(...lengths),milliseconds,minX,south};});
fs.mkdirSync('reports/v5',{recursive:true});fs.writeFileSync('reports/v5/minimap-tests.json',JSON.stringify({passed:results.every(r=>r.passed),results},null,2));if(results.some(r=>!r.passed))process.exitCode=1;
