import fs from 'node:fs';
import assert from 'node:assert/strict';
import * as T from 'three';
import {applyPathBrush,brushShape} from '../preview/map-brush.js';
import {createPath,createPlaza,rebuildSurfaces} from '../preview/map-surfaces.js';
import {WorldEditor} from '../preview/editor.js';
import {ExperienceManager} from '../preview/experiences.js';
import {applyTerrainOperation} from '../preview/map-terrain.js';
import {surfaceMaterial,surfaceUV} from '../preview/surface-materials.js';
import {portableObjectJSON} from '../preview/world-instances.js';
import {createRoad,rebuildRoad,roadGeometryData} from '../preview/roads/road-system.js';
import {worldFiles,WORLD_SLOTS} from '../preview/world-storage.js';
const results=[];function test(name,fn){try{const data=fn();results.push({name,passed:true,data});console.log('PASS',name);}catch(e){results.push({name,passed:false,error:e.stack});console.error('FAIL',name,e);}}
const hit=(root,x,z)=>{root.updateMatrixWorld(true);const meshes=[];root.traverseVisible(o=>{if(o.isMesh&&!o.userData.deleted)meshes.push(o);});return new T.Raycaster(new T.Vector3(x,100,z),new T.Vector3(0,-1,0)).intersectObjects(meshes,false);};
function editorFor(root){const e=Object.create(WorldEditor.prototype);Object.assign(e,{root,registry:new Map(),baseline:new Map(),history:[],future:[],selected:[],fillTransform(){},updateOutlines(){},notify(){},updateHistory(){},select(n){this.selected=n;}});e.experiences=new ExperienceManager(e);e.experiences.register(root);return e;}
test('A freehand stroke has circular caps, supports a click and rejects invalid coordinates',()=>{assert(brushShape([[0,0]],2).length===1);const root=new T.Group();applyPathBrush(root,[[0,0],[10,2],[20,0]],{radius:2});assert(hit(root,-1,0).length);assert(hit(root,21,0).length);assert(!hit(root,0,3).length);assert.throws(()=>brushShape([[NaN,0]],2));return {roundCaps:true,singleClick:true};});
test('Path eraser removes only the swept strip, including original curves and plazas',()=>{const root=new T.Group(),path=createPath({points:[[-10,.15,0],[10,.15,0]],width:4}),plaza=createPlaza({polygon:[[-5,6],[5,6],[5,12],[-5,12]]});root.add(path,plaza);const ids=[path.uuid,plaza.uuid];applyPathBrush(root,[[0,-5],[0,15]],{kind:'erase',radius:1});assert(!hit(root,0,0).length);assert(!hit(root,0,9).length);assert(hit(root,-4,0).length);assert(hit(root,4,9).length);assert.deepEqual(root.children.map(n=>n.uuid),ids);return {objectsPreserved:2,partialCut:true};});
test('Overlapping brush strokes union and repaint an erased patch without stacked triangles',()=>{const root=new T.Group();applyPathBrush(root,[[-8,0],[8,0]],{radius:2});applyPathBrush(root,[[0,-8],[0,8]],{radius:2});assert.equal(root.children.length,1);const before=root.children[0].userData.surfaceStats.area;applyPathBrush(root,[[0,0]],{kind:'erase',radius:1});assert(!hit(root,.123,.087).length);applyPathBrush(root,[[0,0]],{radius:1.2});assert.equal(root.children.length,1);assert.equal(hit(root,.123,.087).length,1);assert(Math.abs(root.children[0].userData.surfaceStats.area-before)<.001);return {oneSurface:true,refilled:true};});
test('Hidden and locked surfaces are not erased; transformed paths cut in world coordinates',()=>{const root=new T.Group(),path=createPath({points:[[-10,.15,0],[10,.15,0]],width:3});path.position.set(20,0,20);path.rotation.y=Math.PI/2;root.add(path);rebuildSurfaces(root);const before=path.userData.surfaceStats.area;applyPathBrush(root,[[20,20]],{kind:'erase',radius:2,canEdit:()=>false});assert.equal(path.userData.surfaceStats.area,before);applyPathBrush(root,[[20,20]],{kind:'erase',radius:2});assert(!hit(root,20,20).length);assert(hit(root,20,25).length);return {worldSpaceCut:true,lockRespected:true};});
test('Brush strokes use one shared Undo step and survive full ObjectLoader reload with fixed UV density',()=>{const root=new T.Group(),e=editorFor(root);e.mutate(()=>applyPathBrush(root,[[0,0],[12,3],[18,0]],{register:n=>e.register(n),radius:1.5}));const node=root.children[0],before=JSON.stringify(node.userData.surfaceDefinition);assert.equal(e.history.length,1);e.mutate(()=>applyPathBrush(root,[[8,-8],[8,8]],{kind:'erase',radius:2}));assert(!hit(root,8,1).length);e.undo();assert.equal(JSON.stringify(node.userData.surfaceDefinition),before);e.redo();assert(!hit(root,8,1).length);const loaded=new T.ObjectLoader().parse(root.toJSON());rebuildSurfaces(loaded);assert(!hit(loaded,8,1).length);assert(hit(loaded,2,0).length);loaded.children[0].scale.setScalar(2);rebuildSurfaces(loaded);const n=loaded.children[0],p=n.geometry.attributes.position,uv=n.geometry.attributes.uv;for(let i=0;i<p.count;i++){const v=new T.Vector3().fromBufferAttribute(p,i).applyMatrix4(n.matrixWorld);assert(Math.abs(uv.getX(i)-v.x*.2)<1e-5);}return {undoRedo:true,reload:true,worldUV:true};});
test('Terrain add and erase brushes extend MAIN land, create water and undo the entire stroke',()=>{const root=new T.Group(),land=new T.Mesh(new T.PlaneGeometry(20,20,10,10).rotateX(-Math.PI/2),new T.MeshStandardMaterial({side:T.DoubleSide}));land.position.y=.15;land.userData={terrain:true,collision:true};root.add(land);const e=editorFor(root),options={materialFactory:surfaceMaterial,uvFor:surfaceUV};e.mutate(()=>applyTerrainOperation(root,{kind:'add',polygons:brushShape([[8,0],[18,2],[22,5]],4),beachWidth:1},options));assert(hit(root,18,2).some(h=>h.point.y>.1));e.mutate(()=>applyTerrainOperation(root,{kind:'erase',polygons:brushShape([[0,-14],[0,14]],2),beachWidth:0},options));assert(!hit(root,0,0).length);e.undo();assert(hit(root,0,0).length);e.undo();assert(!hit(root,18,2).length);return {twoStrokes:2,undoOriginal:true};});
test('Compact road saves regenerate asphalt and markings exactly',()=>{const road=createRoad({points:[[0,.205,0],[20,.205,3],[40,.205,0]],width:7}),json=portableObjectJSON(road),restored=new T.ObjectLoader().parse(json);rebuildRoad(restored);assert.deepEqual(Array.from(restored.geometry.attributes.position.array),Array.from(road.geometry.attributes.position.array));assert.equal(roadGeometryData(restored).def.width,7);return {bytes:JSON.stringify(json).length};});
test('Archipelago is the sole default and query parameters cannot select another world',()=>{assert.deepEqual(Object.keys(WORLD_SLOTS),['archipelago']);for(const query of ['', '?world=original','?world=lagoon','?world=coast','?world=../../bad']){const files=worldFiles(query);assert.equal(files.id,'archipelago');assert.equal(files.world,'../exports/worlds/archipelago/editor-world.json.gz');assert.equal(files.api('world'),'/api/world?world=archipelago');}});
fs.mkdirSync('reports/v7',{recursive:true});fs.writeFileSync('reports/v7/brush-tests.json',JSON.stringify(results,null,2));if(results.some(r=>!r.passed))process.exitCode=1;
