import * as THREE from 'three';
import {updatePrefabTerrain} from './prefab-terrain.js';
import {paintLand} from './land-builder.js';
import {authoringPreview} from './world2-gameplay.js';
import {TransformControls} from 'three/addons/controls/TransformControls.js';
import {GLTFExporter} from 'three/addons/exporters/GLTFExporter.js';
import {GLTFLoader} from 'three/addons/loaders/GLTFLoader.js';
const $=s=>document.querySelector(s),clone=v=>JSON.parse(JSON.stringify(v));
function visibleBounds(root){const box=new THREE.Box3();root.updateWorldMatrix(true,true);root.traverseVisible(o=>{if(!o.isMesh)return;if(o.isInstancedMesh){o.computeBoundingBox();box.union(o.boundingBox.clone().applyMatrix4(o.matrixWorld));}else{if(!o.geometry.boundingBox)o.geometry.computeBoundingBox();box.union(o.geometry.boundingBox.clone().applyMatrix4(o.matrixWorld));}});return box;}
export class WorldEditor {
 constructor(scene,root,camera,renderer,orbit,notify,catalog){
  Object.assign(this,{scene,root,camera,renderer,orbit,notify,catalog});this.enabled=true;this.selected=[];this.registry=new Map();this.history=[];this.future=[];this.dirty=false;this.ray=new THREE.Raycaster();this.pointer=new THREE.Vector2();this.roadHandles=[];this.assetTemplates=[];this.activePoint=0;this.brush=false;this.down=null;
  this.baseline=new Map();const index=(o,path='scene')=>{o.userData.aw_id??=path;this.registry.set(o.userData.aw_id,o);this.baseline.set(o.userData.aw_id,{geometry:o.geometry,material:o.material});o.children.forEach((n,i)=>index(n,o.userData.aw_id+'/'+i));};index(root);this.multiPivot=new THREE.Object3D();scene.add(this.multiPivot);this.gizmo=new TransformControls(camera,renderer.domElement);scene.add(this.gizmo.getHelper());this.gizmo.setSize(.85);
  this.gizmo.addEventListener('dragging-changed',e=>{orbit.enabled=!e.value;if(e.value){this.startChange();if(this.selected.length>1){this.multiPivot.updateMatrixWorld(true);this.multiStart=this.multiPivot.matrixWorld.clone().invert();this.multiMatrices=this.selected.map(o=>{o.updateWorldMatrix(true,false);return o.matrixWorld.clone();});}}else{if(this.pointOwner){this.updateRoadPoint();}else if($('#snap-ground').checked&&this.gizmo.mode==='translate')this.selected.forEach(o=>this.drop(o));this.endChange();}});
  this.gizmo.addEventListener('objectChange',()=>{if(this.pointOwner)this.updateRoadPoint();else if(this.selected.length>1&&this.multiStart){this.multiPivot.updateMatrixWorld(true);const delta=this.multiPivot.matrixWorld.clone().multiply(this.multiStart);this.selected.forEach((o,i)=>{const matrix=o.parent.matrixWorld.clone().invert().multiply(delta).multiply(this.multiMatrices[i]);matrix.decompose(o.position,o.quaternion,o.scale);});}for(const o of this.selected)if(o.userData.world2Feature){o.rotation.x=0;o.rotation.z=0;if(this.gizmo.mode==='scale'){const axis=this.gizmo.axis?.toLowerCase();o.scale.setScalar(Math.max(.01,['x','y','z'].includes(axis)?o.scale[axis]:o.scale.x));}}this.updateOutlines();this.fillTransform();});
  this.bind();this.buildAssets();this.select([]);this.updateHistory();
 }
 isVisible(o){for(let p=o;p;p=p.parent)if(!p.visible||p.userData.deleted)return false;return true;}
 editRoot(o){for(let p=o;p&&p!==this.root;p=p.parent){if(p.userData.editable_root)return p;}return o;}
 meshes(){const a=[];this.root.traverse(o=>{if(o.isMesh&&this.isVisible(o)&&!o.userData.unselectable)a.push(o);});return a;}
 rayAt(e){const r=this.renderer.domElement.getBoundingClientRect();this.pointer.set((e.clientX-r.left)/r.width*2-1,-(e.clientY-r.top)/r.height*2+1);this.ray.setFromCamera(this.pointer,this.camera);return this.ray;}
 groundAt(e){this.rayAt(e);return this.ray.intersectObjects(this.meshes().filter(o=>o.userData.ground_surface||o.userData.terrain||(!this.brush&&o.userData.collision&&o.userData.physics_mode!=='DYNAMIC')),false)[0];}
 bind(){const canvas=this.renderer.domElement;
  canvas.addEventListener('pointerdown',e=>{if(!this.enabled||e.button!==0)return;this.down={x:e.clientX,y:e.clientY};if(this.brush){this.startChange();this.painting=true;this.flattenHeight=null;this.orbit.enabled=false;this.paint(e);}});
  canvas.addEventListener('pointermove',e=>{if(this.painting)this.paint(e);});
  canvas.addEventListener('pointerup',e=>{if(!this.enabled)return;if(this.painting){this.painting=false;this.orbit.enabled=true;this.endChange();return;}if(!this.down||Math.hypot(e.clientX-this.down.x,e.clientY-this.down.y)>5||this.gizmo.dragging||this.gizmo.axis)return;this.rayAt(e);const handle=this.ray.intersectObjects(this.roadHandles)[0];if(handle){this.activePoint=handle.object.userData.index;this.pointOwner=this.selected[0];this.gizmo.attach(handle.object);return;}const hit=this.ray.intersectObjects(this.meshes(),false)[0];if(hit){const o=this.editRoot(hit.object);if(e.shiftKey)this.select(this.selected.includes(o)?this.selected.filter(x=>x!==o):[...this.selected,o]);else this.select([o]);}else this.select([]);});
  canvas.addEventListener('dragover',e=>{e.preventDefault();e.dataTransfer.dropEffect='copy';if(this.dragAssetIndex!==undefined&&this.enabled){const hit=this.groundAt(e);if(hit){if(!this.ghost){this.ghost=this.assetTemplates[this.dragAssetIndex].node.clone(true);this.ghost.traverse(o=>{if(o.isMesh){o.material=(Array.isArray(o.material)?o.material:[o.material]).map(m=>{const n=m.clone();n.transparent=true;n.opacity=.5;n.depthWrite=false;return n;});if(o.material.length===1)o.material=o.material[0];}});this.scene.add(this.ghost);}this.ghost.position.copy(hit.point);if($('#snap-grid').checked)this.ghost.position.round();this.drop(this.ghost);}}});canvas.addEventListener('drop',e=>{e.preventDefault();if(!this.enabled)return;const id=e.dataTransfer.getData('text/plain'),hit=this.groundAt(e);if(hit)this.placeAsset(Number(id),hit.point,hit.face?.normal);this.clearGhost();});
  document.querySelectorAll('[data-tool]').forEach(b=>b.onclick=()=>this.setTool(b.dataset.tool));
  $('#undo').onclick=()=>this.undo();$('#redo').onclick=()=>this.redo();$('#save').onclick=()=>this.save();$('#export-glb').onclick=()=>this.exportGLB();$('#object-name').onchange=e=>this.mutate(()=>{this.selected[0].name=e.target.value;this.select(this.selected);});
  $('#duplicate').onclick=()=>this.duplicate();$('#delete').onclick=()=>this.remove();$('#focus').onclick=()=>this.focus();$('#drop').onclick=()=>this.mutate(()=>this.selected.forEach(o=>this.drop(o)));$('#random-rotate').onclick=()=>this.mutate(()=>this.selected.forEach(o=>o.rotation.y=Math.random()*Math.PI*2));$('#create-collision').onclick=()=>this.mutate(()=>this.selected.forEach(o=>{o.userData.collision=true;o.userData.collision_shape='CONVEX_HULL';this.fillProperties();}));
  $('#snap-grid').onchange=e=>this.gizmo.setTranslationSnap(e.target.checked?1:null);$('#snap-rotation').onchange=e=>this.gizmo.setRotationSnap(e.target.checked?Math.PI/12:null);
  for(const [id,key] of [['physics-mode','physics_mode'],['mass','mass'],['friction','friction'],['restitution','restitution'],['collision','collision']])$('#'+id).onchange=e=>this.mutate(()=>{for(const o of this.selected)o.userData[key]=e.target.type==='checkbox'?e.target.checked:e.target.tagName==='SELECT'?e.target.value:Number(e.target.value);});
  for(const [id,key] of [['mat-color','color'],['mat-rough','roughness'],['mat-metal','metalness']])$('#'+id).onchange=e=>this.mutate(()=>this.materials(m=>{if(key==='color')m.color.set(e.target.value);else m[key]=Number(e.target.value);}));
  $('#mat-texture').onchange=async e=>{const f=e.target.files[0];if(!f)return;const data=await new Promise(resolve=>{const r=new FileReader();r.onload=()=>resolve(r.result);r.readAsDataURL(f);});this.mutate(()=>this.materials(m=>{m.map=new THREE.TextureLoader().load(data);m.map.colorSpace=THREE.SRGBColorSpace;m.needsUpdate=true;m.userData.editorTexture=data;}));};
  $('#road-width').onchange=e=>this.mutate(()=>{const o=this.selected[0];o.userData.road_width=Math.max(2,Number(e.target.value));this.rebuildRoad(o);});
  for(const [id,key] of [['rail-left','rail_left'],['rail-right','rail_right']])$('#'+id).onchange=e=>this.mutate(()=>{const o=this.selected[0];o.userData[key]=e.target.checked;this.rebuildRoad(o);});
  $('#road-add').onclick=()=>this.roadAction('add');$('#road-delete').onclick=()=>this.roadAction('delete');$('#road-extend').onclick=()=>this.roadAction('extend');
  $('#terrain-tool').onclick=()=>{this.brush=!this.brush;$('#terrain-tool').classList.toggle('active',this.brush);$('#terrain-properties').open=this.brush;document.body.classList.toggle('terrain-active',this.brush);if(this.brush){this.gizmo.detach();this.notify('Pincel de terreno activo · arrastra para esculpir');}};
  $('#search').oninput=()=>this.filterAssets();$('#category').onchange=()=>this.filterAssets();$('#import').onclick=()=>$('#import-file').click();$('#import-file').onchange=e=>this.importFile(e.target.files[0]);
  for(const prop of ['position','rotation','scale']){const div=document.createElement('div');div.innerHTML=`<small>${prop[0].toUpperCase()+prop.slice(1)}</small><div class="vector">${['x','y','z'].map(axis=>`<label>${axis.toUpperCase()}<input type="number" step="${prop==='rotation'?5:.1}" data-prop="${prop}" data-axis="${axis}" aria-label="${prop} ${axis}"></label>`).join('')}</div>`;$('#transform-fields').append(div);}
  document.querySelectorAll('[data-prop]').forEach(el=>el.onchange=()=>this.mutate(()=>{const o=this.selected[0],n=Number(el.value);if(!Number.isFinite(n))return;o[el.dataset.prop][el.dataset.axis]=el.dataset.prop==='rotation'?THREE.MathUtils.degToRad(n):el.dataset.prop==='scale'?Math.max(.01,n):n;if(o.userData.world2Asset){o.rotation.x=0;o.rotation.z=0;if(el.dataset.prop==='scale')o.scale.setScalar(Math.max(.01,n));}this.updateOutlines();}));
  addEventListener('keydown',e=>{if(!this.enabled||e.target.matches('input,select,textarea'))return;const mod=e.metaKey||e.ctrlKey;if(mod&&e.code==='KeyZ'){e.preventDefault();e.shiftKey?this.redo():this.undo();return;}if(mod&&e.code==='KeyS'){e.preventDefault();this.save();return;}if(mod&&e.code==='KeyD'){e.preventDefault();this.duplicate();return;}if(['Delete','Backspace'].includes(e.code)){e.preventDefault();this.remove();}if(['KeyG','KeyW'].includes(e.code))this.setTool('translate');if(['KeyR','KeyE'].includes(e.code))this.setTool('rotate');if(e.code==='KeyS'&&!mod)this.setTool('scale');if(e.code==='KeyF')this.focus();if(e.code==='Escape'){this.brush=false;$('#terrain-tool').classList.remove('active');document.body.classList.remove('terrain-active');this.select([]);}});
  for(const el of document.querySelectorAll('#object-properties input,#object-properties select')){if(el.onchange)el.onblur=el.onchange;el.addEventListener('keydown',e=>{if(e.key==='Enter'){el.blur();}});}
  setInterval(()=>{if($('#autosave').checked&&this.dirty&&this.enabled)this.save(true);},30000);
 }
 setTool(mode){this.brush=false;$('#terrain-tool').classList.remove('active');document.body.classList.remove('terrain-active');this.gizmo.setMode(mode);document.querySelectorAll('[data-tool]').forEach(b=>b.classList.toggle('active',b.dataset.tool===mode));}
 select(items){this.clearHandles();this.pointOwner=null;this.gizmo.detach();this.selected=items;document.body.classList.toggle('has-selection',items.length>0);$('#object-properties').hidden=!items.length;$('#empty-selection').hidden=!!items.length;$('#selection-count').textContent=items.length?String(items.length):'—';$('#selected-status').textContent=items.length?items.map(o=>o.name).join(' + '):'Nothing selected';
  if(items.length===1){this.gizmo.attach(items[0]);if(items[0].userData.road_points)this.showHandles(items[0]);}else if(items.length>1){const center=new THREE.Vector3();items.forEach(o=>center.add(o.getWorldPosition(new THREE.Vector3())));center.divideScalar(items.length);this.multiPivot.position.copy(center);this.multiPivot.quaternion.identity();this.multiPivot.scale.set(1,1,1);this.gizmo.attach(this.multiPivot);}
  this.fillProperties();this.updateOutlines();
 }
 updateOutlines(){updatePrefabTerrain(this.root);for(const h of this.outlines||[]){h.removeFromParent();h.geometry.dispose();h.material.dispose();}this.outlines=this.selected.filter(o=>!o.userData.terrain).map(o=>{o.updateWorldMatrix(true,true);const h=new THREE.BoxHelper(o,0x8ee1c4);this.scene.add(h);return h;});}
 fillTransform(){const o=this.selected[0];if(!o)return;for(const el of document.querySelectorAll('[data-prop]')){const v=o[el.dataset.prop][el.dataset.axis];el.value=(el.dataset.prop==='rotation'?THREE.MathUtils.radToDeg(v):v).toFixed(2);}}
 firstMaterial(){let m;this.selected[0]?.traverse(o=>{if(!m&&o.isMesh)m=Array.isArray(o.material)?o.material[0]:o.material;});return m;}
 fillProperties(){const o=this.selected[0];if(!o)return;$('#object-name').value=o.name;this.fillTransform();const m=this.firstMaterial();if(m?.color){$('#mat-color').value='#'+m.color.getHexString();$('#mat-rough').value=m.roughness??.7;$('#mat-metal').value=m.metalness??0;}$('#physics-mode').value=o.userData.physics_mode||'STATIC';for(const [id,def] of [['mass',1],['friction',.7],['restitution',.1]])$('#'+id).value=o.userData[id]??def;$('#collision').checked=!!o.userData.collision;$('#road-properties').hidden=!o.userData.road_points;$('#road-width').value=o.userData.road_width||7;$('#rail-left').checked=!!o.userData.rail_left;$('#rail-right').checked=!!o.userData.rail_right;}
 materials(fn){for(const root of this.selected)root.traverse(o=>{if(o.isMesh){if(!o.userData.privateMaterial){o.material=Array.isArray(o.material)?o.material.map(m=>m.clone()):o.material.clone();o.userData.privateMaterial=true;}for(const m of Array.isArray(o.material)?o.material:[o.material])fn(m);o.userData.materialEdited=true;}});}
 capture(){const states={};for(const [id,o] of this.registry){const s={name:o.name,p:o.position.toArray(),q:o.quaternion.toArray(),s:o.scale.toArray(),visible:o.visible,data:clone(o.userData)};if(o.userData.materialEdited&&o.isMesh)s.materials=(Array.isArray(o.material)?o.material:[o.material]).map(m=>({color:m.color?.getHex(),roughness:m.roughness,metalness:m.metalness,texture:m.userData.editorTexture}));if(o.userData.geometryEdited&&o.isMesh)s.geometry={position:Array.from(o.geometry.attributes.position.array),color:o.geometry.attributes.color?Array.from(o.geometry.attributes.color.array):null};states[id]=s;}return states;}
 startChange(){this.before=this.capture();}
 endChange(){if(!this.before)return;const after=this.capture();if(JSON.stringify(after)!==JSON.stringify(this.before)){this.history.push({before:this.before,after});if(this.history.length>35)this.history.shift();this.future=[];this.dirty=true;}this.before=null;this.updateHistory();this.fillTransform();this.updateOutlines();}
 mutate(fn){if(!this.selected.length&&fn!==undefined&&false)return;this.startChange();fn();this.endChange();}
 apply(states){this.select([]);for(const [id,o] of this.registry){const s=states[id];if(!s){if(o.userData.added){o.visible=false;o.userData.deleted=true;}continue;}o.name=s.name;o.position.fromArray(s.p);o.quaternion.fromArray(s.q);o.scale.fromArray(s.s);o.visible=s.visible;o.userData=clone(s.data);const base=this.baseline.get(id);if(!s.geometry&&!s.data.roadEdited&&base?.geometry)o.geometry=base.geometry;if(!s.materials&&base?.material)o.material=base.material;if(s.materials&&o.isMesh){o.material=(Array.isArray(o.material)?o.material:[o.material]).map((m,i)=>{const n=m.clone(),a=s.materials[i];if(a){if(n.color)n.color.setHex(a.color);n.roughness=a.roughness;n.metalness=a.metalness;if(a.texture){n.map=new THREE.TextureLoader().load(a.texture);n.map.colorSpace=THREE.SRGBColorSpace;n.userData.editorTexture=a.texture;}}return n;});if(o.material.length===1)o.material=o.material[0];}if(s.geometry&&o.isMesh){o.geometry=o.geometry.clone();o.geometry.setAttribute('position',new THREE.Float32BufferAttribute(s.geometry.position,3));if(s.geometry.color)o.geometry.setAttribute('color',new THREE.Float32BufferAttribute(s.geometry.color,3));o.geometry.computeVertexNormals();o.geometry.computeBoundingSphere();}if(o.userData.roadEdited)this.rebuildRoad(o);}
  updatePrefabTerrain(this.root,true);this.dirty=true;this.updateHistory();}
 undo(){const cmd=this.history.pop();if(!cmd)return;this.future.push(cmd);this.apply(cmd.before);this.notify('Cambio deshecho');}
 redo(){const cmd=this.future.pop();if(!cmd)return;this.history.push(cmd);this.apply(cmd.after);this.notify('Cambio rehecho');}
 updateHistory(){$('#undo').disabled=!this.history.length;$('#redo').disabled=!this.future.length;$('#world-status').textContent=this.dirty?'CHANGES NOT SAVED':'LOCAL WORLD · SAVED';}
 register(o){o.traverse(n=>{n.userData={...n.userData,aw_id:'user:'+THREE.MathUtils.generateUUID(),aw_template:false};this.registry.set(n.userData.aw_id,n);this.baseline.set(n.userData.aw_id,{geometry:n.geometry,material:n.material});});o.userData.added=true;o.userData.editable_root=true;o.visible=true;return o;}
 duplicate(){if(!this.selected.length)return;this.mutate(()=>{const copies=this.selected.map(o=>{const n=this.register(o.clone(true));n.name=o.name+' copy';n.position.x+=3;this.root.add(n);return n;});this.select(copies);});}
 remove(){if(!this.selected.length)return;this.mutate(()=>{for(const o of this.selected){o.visible=false;o.userData.deleted=true;}this.select([]);});}
 drop(o){if(o.userData.world2Asset){const own=new Set();o.traverse(n=>own.add(n));const ray=new THREE.Raycaster(new THREE.Vector3(o.position.x,200,o.position.z),new THREE.Vector3(0,-1,0));const hit=ray.intersectObjects(this.meshes().filter(n=>!own.has(n)&&(n.userData.terrain||n.userData.ground_surface)),false)[0];if(hit)o.position.y=hit.point.y+.025;return;}o.updateWorldMatrix(true,true);const box=new THREE.Box3().setFromObject(o),p=box.getCenter(new THREE.Vector3());p.y=box.max.y+100;const ray=new THREE.Raycaster(p,new THREE.Vector3(0,-1,0)),own=new Set();o.traverse(n=>own.add(n));const hit=ray.intersectObjects(this.meshes().filter(n=>!own.has(n)&&(n.userData.ground_surface||n.userData.terrain||(n.userData.collision&&n.userData.physics_mode!=='DYNAMIC'))),false)[0];if(hit){o.position.y+=hit.point.y-box.min.y+.01;if($('#align-ground').checked&&hit.face){const normal=hit.face.normal.clone().transformDirection(hit.object.matrixWorld);o.quaternion.premultiply(new THREE.Quaternion().setFromUnitVectors(new THREE.Vector3(0,1,0).applyQuaternion(o.quaternion).normalize(),normal));}}o.updateWorldMatrix(true,true);}
 focus(){if(!this.selected.length)return;const b=new THREE.Box3();this.selected.forEach(o=>b.union(visibleBounds(o)));const c=b.getCenter(new THREE.Vector3()),r=Math.max(5,b.getSize(new THREE.Vector3()).length());this.orbit.target.copy(c);this.camera.position.copy(c).add(new THREE.Vector3(.8,.8,1).multiplyScalar(r));this.camera.lookAt(c);}
 roadPoints(o){return typeof o.userData.road_points==='string'?JSON.parse(o.userData.road_points):o.userData.road_points;}
 clearHandles(){for(const h of this.roadHandles){h.removeFromParent();h.geometry.dispose();h.material.dispose();}this.roadHandles=[];}
 showHandles(o){this.clearHandles();this.roadPoints(o).forEach((p,i)=>{const h=new THREE.Mesh(new THREE.SphereGeometry(.65,10,8),new THREE.MeshBasicMaterial({color:0x75c5fa,depthTest:false}));h.position.fromArray(p).applyMatrix4(o.matrixWorld);h.position.y+=.3;h.userData.index=i;h.renderOrder=1000;this.scene.add(h);this.roadHandles.push(h);});}
 updateRoadPoint(){const o=this.pointOwner,h=this.roadHandles[this.activePoint];if(!o||!h)return;const p=h.position.clone();p.y-=.3;p.applyMatrix4(o.matrixWorld.clone().invert());const points=this.roadPoints(o);points[this.activePoint]=p.toArray();o.userData.road_points=JSON.stringify(points);this.rebuildRoad(o);}
 roadAction(action){const o=this.selected[0];if(!o?.userData.road_points)return;this.mutate(()=>{const points=this.roadPoints(o),i=Math.min(this.activePoint,points.length-1);if(action==='delete'){if(points.length>3)points.splice(i,1);}else if(action==='extend'){const a=new THREE.Vector3().fromArray(points.at(-1)),b=new THREE.Vector3().fromArray(points.at(-2));points.push(a.clone().add(a.clone().sub(b).normalize().multiplyScalar(8)).toArray());o.userData.road_closed=false;}else{const a=new THREE.Vector3().fromArray(points[i]),b=new THREE.Vector3().fromArray(points[(i+1)%points.length]);points.splice(i+1,0,a.lerp(b,.5).toArray());}o.userData.road_points=JSON.stringify(points);this.rebuildRoad(o);this.select([o]);});}
 rebuildRoad(o){const pts=this.roadPoints(o).map(p=>new THREE.Vector3(...p)),curve=new THREE.CatmullRomCurve3(pts,!!o.userData.road_closed,'catmullrom',.5),points=curve.getPoints(Math.max(64,pts.length*16)),vertices=[],indices=[],normals=[];const width=o.userData.road_width||7;
  points.forEach((p,i)=>{const t=points[Math.min(i+1,points.length-1)].clone().sub(points[Math.max(0,i-1)]).normalize(),n=new THREE.Vector3(-t.z,0,t.x).normalize();for(const sign of [-1,1]){vertices.push(...p.clone().addScaledVector(n,sign*width/2).toArray());normals.push(0,1,0);}if(i){const k=i*2;indices.push(k-2,k-1,k,k-1,k+1,k);}});
  const geo=new THREE.BufferGeometry();geo.setAttribute('position',new THREE.Float32BufferAttribute(vertices,3));geo.setAttribute('normal',new THREE.Float32BufferAttribute(normals,3));geo.setIndex(indices);geo.computeBoundingSphere();o.geometry=geo;o.userData.roadEdited=true;
  for(const n of [...o.children])if(n.userData.generatedRoadDetail){n.removeFromParent();n.geometry?.dispose();}
  for(const side of [-1,1])if(o.userData[side<0?'rail_left':'rail_right']){const ps=points.map((p,i)=>{const t=points[Math.min(i+1,points.length-1)].clone().sub(points[Math.max(0,i-1)]).normalize();return p.clone().add(new THREE.Vector3(-t.z*.5*width*side,.65,t.x*.5*width*side));});const rail=new THREE.Mesh(new THREE.TubeGeometry(new THREE.CatmullRomCurve3(ps),ps.length,.075,5,false),new THREE.MeshStandardMaterial({color:0xd6ded6}));rail.userData.generatedRoadDetail=true;o.add(rail);}
  // Hide original edge stripes when their road is reshaped, not unrelated roads.
  this.root.traverse(n=>{if(n!==o&&n.name.startsWith(o.name+' edge'))n.visible=false;});
 }
 paint(e){const modeNow=$('#brush-mode').value;if(modeNow==='Create land'||modeNow==='Erase land'){this.rayAt(e);const p=new THREE.Vector3();if(this.ray.ray.intersectPlane(new THREE.Plane(new THREE.Vector3(0,1,0),1.2),p)){paintLand(this,p,Number($('#brush-radius').value),Number($('#land-height').value),modeNow==='Erase land');}return;}this.landBaseCache=null;const hit=this.groundAt(e);if(!hit)return;const o=hit.object;if(!o.userData.sculptable)return;const g=o.geometry;if(!o.userData.geometryEdited){o.geometry=g.clone();o.userData.geometryEdited=true;}const geo=o.geometry,pos=geo.attributes.position,rad=Number($('#brush-radius').value),strength=Number($('#brush-strength').value),mode=$('#brush-mode').value;const target=o.worldToLocal(hit.point.clone());let colors=geo.attributes.color;if(!colors){const a=new Float32Array(pos.count*3);a.fill(.5);geo.setAttribute('color',new THREE.BufferAttribute(a,3));colors=geo.attributes.color;}
  if(this.flattenHeight===null)this.flattenHeight=target.y;
  if(mode==='Smooth'&&this.smoothGraph?.geometry!==geo){const groups=new Map(),key=i=>pos.getX(i).toFixed(4)+','+pos.getZ(i).toFixed(4);for(let i=0;i<pos.count;i++){const k=key(i);if(!groups.has(k))groups.set(k,{indices:[],neighbors:new Set()});groups.get(k).indices.push(i);}const idx=geo.index?.array||Array.from({length:pos.count},(_,i)=>i);for(let i=0;i<idx.length;i+=3)for(const a of [idx[i],idx[i+1],idx[i+2]])for(const b of [idx[i],idx[i+1],idx[i+2]])if(key(a)!==key(b))groups.get(key(a)).neighbors.add(key(b));this.smoothGraph={groups,key,geometry:geo};}
  const averages=new Map();if(mode==='Smooth'){const {groups}=this.smoothGraph;for(const [k,g] of groups){let total=0,n=0;for(const next of g.neighbors){total+=pos.getY(groups.get(next).indices[0]);n++;}averages.set(k,n?total/n:pos.getY(g.indices[0]));}}
  const paint={Grass:0x789847,Sand:0xcbbb87,Rock:0x82867c,Snow:0xe0eeeb,Dirt:0x896a45},c=new THREE.Color(paint[$('#brush-paint').value]);
  for(let i=0;i<pos.count;i++){const d=Math.hypot(pos.getX(i)-target.x,pos.getZ(i)-target.z);if(d>rad)continue;const w=(1-d/rad)*strength;if(mode==='Paint'){colors.setXYZ(i,THREE.MathUtils.lerp(colors.getX(i),c.r,w),THREE.MathUtils.lerp(colors.getY(i),c.g,w),THREE.MathUtils.lerp(colors.getZ(i),c.b,w));}else{const y=pos.getY(i);pos.setY(i,mode==='Raise'?y+w*.6:mode==='Lower'?y-w*.6:THREE.MathUtils.lerp(y,mode==='Smooth'?averages.get(this.smoothGraph.key(i)):this.flattenHeight,w));}}
  pos.needsUpdate=true;colors.needsUpdate=true;geo.computeVertexNormals();geo.computeBoundingSphere();}
 buildAssets(){const specs=[['Broadleaf tree','Trees',/^Tree\d*|^Tree$/],['Pine','Trees',/^Pine\d*|^Pine$/],['Coastal rock','Rocks',/^Coastal rock/],['Penguin','Ice',/^Learner penguin/],['Traffic cone','Props',/^Ice cone/],['Bench','Decoration',/^Garden bench/],['Lamp','Decoration',/^Boulevard lamp/],['AN roadster','Vehicles',/^Parked AN roadster/],['Lab robot','Characters',/^Lab assistant/],['Town hall','Buildings',/^About house/],['Kiosk','Fairground',/^Fairground kiosk/],['Laptop','Technology',/^Studio laptop/],['Server rack','Technology',/^Server rack/],['Camera','Technology',/^Studio camera/],['Garage','Racing',/^Pit garage/],['Trophy','Props',/^Achievement trophy/],['Flowering shrub','Plants',/^Flowering shrub/],['Low bush','Plants',/^Low bush/]];
  for(const [label,category,re] of specs){let found;this.root.traverse(o=>{if(!found&&re.test(o.name.replaceAll('_',' ')))found=o;});if(found)this.assetTemplates.push({label,category,node:found});}
  const road=new THREE.Mesh(new THREE.PlaneGeometry(12,6),new THREE.MeshStandardMaterial({color:0x384548,side:THREE.DoubleSide}));road.geometry.rotateX(-Math.PI/2);road.userData={road_points:JSON.stringify([[-6,.07,0],[0,.07,0],[6,.07,0]]),road_width:6,road_closed:false,road:true,ground_surface:true,collision:true,surface_type:'road'};this.assetTemplates.push({label:'Editable road',category:'Roads',node:road});
  for(const entry of this.catalog.entries){const node=this.catalog.template(entry);if(entry.feature){node.clear();node.add(authoringPreview(this.catalog,entry));}this.assetTemplates.push({label:entry.label,category:entry.category,node});}
  const categories=['World2 · actividades','All','World2 · conjuntos','World2 · objetos','World2 · naturaleza','Nature','Trees','Plants','Rocks','Roads','Buildings','Vehicles','Characters','Props','Racing','Ice','Fairground','Technology','Decoration','Imported'];$('#category').innerHTML=categories.map(c=>`<option>${c}</option>`).join('');
  // Thumbnail renderer uses the actual mesh, not category icons.
  this.thumbRenderer=new THREE.WebGLRenderer({antialias:true,alpha:true});this.thumbRenderer.setSize(128,128);this.thumbRenderer.setPixelRatio(1);this.thumbScene=new THREE.Scene();this.thumbScene.add(new THREE.HemisphereLight(0xffffff,0x748b77,3));const l=new THREE.DirectionalLight(0xffffff,3);l.position.set(-3,6,5);this.thumbScene.add(l);this.thumbCamera=new THREE.PerspectiveCamera(38,1,.01,1000);this.filterAssets();
 }
 clearGhost(){if(this.ghost){this.ghost.traverse(o=>{if(o.isMesh)for(const m of Array.isArray(o.material)?o.material:[o.material])m.dispose();});this.ghost.removeFromParent();this.ghost=null;}this.dragAssetIndex=undefined;}
 thumbnail(node){const o=node.clone(true);o.position.set(0,0,0);o.quaternion.identity();o.visible=true;o.updateMatrixWorld(true);const b=visibleBounds(o),c=b.getCenter(new THREE.Vector3()),r=Math.max(.1,b.getSize(new THREE.Vector3()).length());this.thumbScene.add(o);this.thumbCamera.position.copy(c).add(new THREE.Vector3(.7,.55,1).normalize().multiplyScalar(r*1.25));this.thumbCamera.lookAt(c);this.thumbRenderer.render(this.thumbScene,this.thumbCamera);const image=this.thumbRenderer.domElement.toDataURL();o.removeFromParent();return image;}
 filterAssets(){const grid=$('#asset-grid');grid.replaceChildren();const q=$('#search').value.toLowerCase(),cat=$('#category').value;this.assetTemplates.forEach((a,i)=>{if((cat!=='All'&&a.category!==cat)&&!(cat==='Nature'&&['Trees','Rocks','Plants'].includes(a.category)))return;if(!a.label.toLowerCase().includes(q))return;const b=document.createElement('div');b.className='asset';b.draggable=true;b.role='button';b.tabIndex=0;b.title='Colocar '+a.label;const img=new Image();img.src=a.thumbnail??=this.thumbnail(a.node);img.alt=a.label;b.append(img);const text=document.createElement('span');text.textContent=a.label;b.append(text);b.ondragstart=e=>{this.dragAssetIndex=i;e.dataTransfer.setData('text/plain',String(i));};b.ondragend=()=>this.clearGhost();b.onclick=()=>this.placeAsset(i,this.orbit.target.clone());b.onkeydown=e=>{if(e.key==='Enter')b.click();};grid.append(b);});}
 placeAsset(i,point,normal){const asset=this.assetTemplates[i];if(!asset)return;this.startChange();const o=this.register(asset.node.clone(true));o.name=asset.label+' '+String(this.registry.size);o.parent=null;o.position.copy(point);this.root.add(o);o.userData.category=asset.category;if($('#snap-grid').checked)o.position.round();if($('#snap-ground').checked)this.drop(o);if($('#align-ground').checked&&normal)o.quaternion.setFromUnitVectors(new THREE.Vector3(0,1,0),normal);this.select([o]);this.endChange();}
 async importFile(file){if(!file)return;try{const buf=await file.arrayBuffer(),gltf=await new GLTFLoader().parseAsync(buf,'');this.startChange();const o=this.register(gltf.scene);o.name=file.name.replace(/\.[^.]+$/,'');o.userData.category='Imported';o.position.copy(this.orbit.target);this.root.add(o);this.drop(o);this.assetTemplates.push({label:o.name,category:'Imported',node:o});this.select([o]);this.endChange();this.filterAssets();this.notify('Modelo importado. Guarda el mundo para conservarlo.');}catch(e){this.notify('No se pudo importar: usa GLB o GLTF con datos incorporados. '+e.message);}}
 async exportGLB(){try{this.notify('Exportando geometría, materiales y animación…');await this.save(true);const data=await new GLTFExporter().parseAsync(this.root,{binary:true,onlyVisible:true,animations:this.animationClips||[],trs:true});const r=await fetch('/api/export',{method:'POST',headers:{'Content-Type':'model/gltf-binary'},body:data});if(!r.ok)throw Error(await r.text());this.notify('Exportado · exports/EditedWorld.glb · listo para Blender');}catch(e){this.notify('Error de exportación: '+e.message);}}
 async save(auto=false){try{const added=[...this.registry.values()].filter(o=>o.userData.added&&!o.userData.deleted).map(o=>o.toJSON());const doc={schema:2,base:'AlejandroWorld.glb',savedAt:new Date().toISOString(),states:this.capture(),added};const response=await fetch('/api/world',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(doc)});if(!response.ok)throw new Error(await response.text());this.dirty=false;this.updateHistory();if(!auto)this.notify('Mundo guardado · exports/editor-world.json');}catch(e){this.notify('No se pudo guardar: '+e.message);}}
 async restore(){const r=await fetch('../exports/editor-world.json');if(!r.ok)return;const doc=await r.json();if(doc.schema!==2)return;for(const json of doc.added){const o=new THREE.ObjectLoader().parse(json);this.root.add(o);o.traverse(n=>{this.registry.set(n.userData.aw_id,n);this.baseline.set(n.userData.aw_id,{geometry:n.geometry,material:n.material});});}this.apply(doc.states);this.dirty=false;this.updateHistory();this.notify('Cambios guardados restaurados');}
 setEnabled(value){this.enabled=value;this.gizmo.getHelper().visible=value&&this.selected.length>0;for(const h of this.outlines||[])h.visible=value;for(const h of this.roadHandles)h.visible=value;if(!value){this.gizmo.detach();this.brush=false;}else if(this.selected.length===1)this.gizmo.attach(this.selected[0]);}
}
