import * as THREE from 'three';
import {GLTFLoader} from 'three/addons/loaders/GLTFLoader.js';
import {OrbitControls} from 'three/addons/controls/OrbitControls.js';
import {mergeGeometries} from 'three/addons/utils/BufferGeometryUtils.js';
import {Physics,RAPIER} from './runtime/physics.js';
import {Driving} from './runtime/driving.js';
import {WorldEditor} from './editor.js';
import {loadWorld2Catalog} from './world2-catalog.js';
import {updatePrefabTerrain} from './prefab-terrain.js';
import {World2Gameplay,simulationDriver} from './world2-gameplay.js';
const $=s=>document.querySelector(s),canvas=$('#world'),viewport=$('#viewport'),keys=new Set();
let loopOriginalMatrix,catalog,gameplay,simulationContext;
let renderer,scene,camera,orbit,root,editor,physics,driving,mixer,nav,mode='edit',simulating=false,editorCamera,simState,accumulator=0,batches=[],hidden=[],ready=false;
function notice(text){$('#notice').textContent=text;$('#notice').classList.add('show');clearTimeout(notice.timer);notice.timer=setTimeout(()=>$('#notice').classList.remove('show'),3500);}
function ancestor(o,key){for(let p=o;p;p=p.parent)if(p.userData[key])return true;return false;}
function setupPhysics(){updatePrefabTerrain(root,true);physics=new Physics();physics.scene=root;root.updateMatrixWorld(true);const nodes=[];root.traverse(o=>{if(!editor.isVisible(o)||!o.userData.collision||ancestor(o,'animated')||ancestor(o,'world2Asset'))return;let parent=o.parent,owned=false;while(parent&&parent!==root){if(parent.userData.collision)owned=true;parent=parent.parent;}if(!owned)nodes.push(o);});for(const o of nodes)physics.mesh(o);return physics;}
function batch(){
 const eligible=[],instanceGroups=new Map(),mergedGroups=new Map();root.updateMatrixWorld(true);
 root.traverse(o=>{if(!o.isMesh||!editor.isVisible(o)||ancestor(o,'animated')||Array.isArray(o.material)||o.userData.terrain||o.userData.unselectable)return;for(let p=o;p;p=p.parent)if(p.userData.physics_mode==='DYNAMIC')return;eligible.push(o);const at=o.getWorldPosition(new THREE.Vector3()),cell=Math.floor(at.x/48)+':'+Math.floor(at.z/48),key=o.geometry.uuid+':'+o.material.uuid+':'+cell;if(!instanceGroups.has(key))instanceGroups.set(key,[]);instanceGroups.get(key).push(o);});
 const instanced=new Set();for(const group of instanceGroups.values()){if(group.length<3)continue;const m=new THREE.InstancedMesh(group[0].geometry,group[0].material,group.length);group.forEach((o,i)=>{m.setMatrixAt(i,o.matrixWorld);instanced.add(o);hidden.push([o,o.visible]);o.visible=false;});m.castShadow=true;m.receiveShadow=true;m.computeBoundingSphere();scene.add(m);batches.push(m);}
 for(const o of eligible){if(instanced.has(o))continue;const at=o.getWorldPosition(new THREE.Vector3()),key=o.material.uuid+':'+Math.floor(at.x/48)+':'+Math.floor(at.z/48);if(!mergedGroups.has(key))mergedGroups.set(key,[]);mergedGroups.get(key).push(o);}
 for(const objects of mergedGroups.values()){if(objects.length<3)continue;const geometries=objects.map(o=>{let g=o.geometry.clone().applyMatrix4(o.matrixWorld);if(g.index){const n=g.toNonIndexed();g.dispose();g=n;}return g;});const attrs=Object.keys(geometries[0].attributes).filter(k=>geometries.every(g=>g.attributes[k]));for(const g of geometries)for(const k of Object.keys(g.attributes))if(!attrs.includes(k))g.deleteAttribute(k);const geometry=mergeGeometries(geometries,false);if(geometry){const m=new THREE.Mesh(geometry,objects[0].material);m.castShadow=true;m.receiveShadow=true;scene.add(m);batches.push(m);for(const o of objects){hidden.push([o,o.visible]);o.visible=false;}}geometries.forEach(g=>g.dispose());}
}
function unbatch(){batches.forEach(b=>{b.removeFromParent();if(b.isInstancedMesh)b.dispose();else b.geometry.dispose();});batches=[];hidden.forEach(([o,v])=>o.visible=v);hidden=[];}
function resetSimulation(){if(physics){if(gameplay)gameplay.reset();else physics.resetProps();physics.render(1);}mixer?.setTime(0);notice('Simulación restaurada');}
function stopSimulation(){if(!physics)return;unbatch();gameplay?.dispose();gameplay=null;simulationContext?.dispose();simulationContext=null;$('#gameplay-hud').replaceChildren();$('#interact-action').hidden=true;driving?.dispose();driving=null;physics.destroy();physics=null;editor.apply(simState);editor.select(simSelection.map(id=>editor.registry.get(id)).filter(Boolean));editor.dirty=simDirty;editor.updateHistory();mixer.setTime(0);simulating=false;$('#simulate').classList.remove('active');}
let simDirty=false,simSelection=[];
function startSimulation(forDrive=false){simState=editor.capture();simSelection=editor.selected.map(o=>o.userData.aw_id);simDirty=editor.dirty;setupPhysics();if(!forDrive){simulationContext=simulationDriver(physics,orbit.target);gameplay=new World2Gameplay(catalog,scene,root,physics,simulationContext);physics.ticker=simulationContext.ticker;}simulating=true;$('#simulate').classList.add('active');}
function liveNavigation(){const live=JSON.parse(JSON.stringify(nav));live.roads=[];live.prefabSpawns=[];root.updateMatrixWorld(true);root.traverse(o=>{if(!editor.isVisible(o))return;if(o.userData.world2Asset){const spawn=catalog.spawnFor(o);if(spawn)live.prefabSpawns.push(spawn);}if(o.userData.road_points){const points=editor.roadPoints(o).map(p=>new THREE.Vector3(...p).applyMatrix4(o.matrixWorld));const curve=new THREE.CatmullRomCurve3(points,!!o.userData.road_closed,'catmullrom',.5);live.roads.push({name:o.name.replaceAll('_',' '),width:o.userData.road_width,closed:!!o.userData.road_closed,type:o.userData.road_network||'road',samples:curve.getPoints(points.length*16).map(p=>[p.x,-p.z,p.y])});}if(o.userData.aw_loop&&loopOriginalMatrix){const delta=o.matrixWorld.clone().multiply(loopOriginalMatrix.clone().invert());live.loop.points=nav.loop.points.map(([x,y,z])=>{const p=new THREE.Vector3(x,z,-y).applyMatrix4(delta);return [p.x,-p.z,p.y];});}});return live;}
function enterDrive(){if(!ready||mode==='drive')return;const live=liveNavigation();if(editor.selected[0]?.userData.world2Asset)live.directSpawn=catalog.spawnFor(editor.selected[0]);if(editor.selected[0]?.userData.landTile){const land=editor.selected[0],a=land.geometry.attributes.position,centre=new THREE.Box3().setFromObject(land).getCenter(new THREE.Vector3());let best=new THREE.Vector3(0,-Infinity,0);for(let i=0;i<a.count;i++){const p=new THREE.Vector3().fromBufferAttribute(a,i).applyMatrix4(land.matrixWorld);if(p.y>best.y+.01||(Math.abs(p.y-best.y)<.01&&p.distanceToSquared(centre)<best.distanceToSquared(centre)))best=p;}best.y+=1.3;live.directSpawn={name:'Tierra creada',position:best.toArray(),rotation:0};}if(simulating)stopSimulation();editorCamera={p:camera.position.clone(),q:camera.quaternion.clone(),target:orbit.target.clone(),fov:camera.fov,near:camera.near};camera.near=.1;startSimulation(true);driving=new Driving(physics,scene,camera,live,keys);gameplay=new World2Gameplay(catalog,scene,root,physics,driving,{map:()=>$('#map-panel').classList.toggle('open'),help:()=>$('#help-dialog').showModal(),achievements:showAchievements});driving.inputs.events.on('map',a=>{if(a.active)$('#map-panel').classList.toggle('open');});driving.inputs.events.on('achievements',a=>{if(a.active)showAchievements();});driving.inputs.events.on('help',a=>{if(a.active)$('#help-dialog').showModal();});driving.inputs.events.on('mute',a=>{if(a.active)driving.audio.setMuted(!driving.audio.muted);});mode='drive';$('#viewport-label').textContent='DRIVING · PORTFOLIO WORLD2';editor.setEnabled(false);orbit.enabled=false;document.body.classList.add('driving');$('#drive').classList.add('active');$('#edit').classList.remove('active');$('#save').disabled=true;$('#export-glb').disabled=true;batch();resize();canvas.focus();notice('World2 · WASD · Shift boost · B freno · Espacio salto · E interactuar');}
function exitDrive(){if(mode!=='drive')return;keys.clear();stopSimulation();mode='edit';$('#viewport-label').textContent='PERSPECTIVE · WORLD OVERVIEW';editor.setEnabled(true);orbit.enabled=true;camera.position.copy(editorCamera.p);camera.quaternion.copy(editorCamera.q);camera.fov=editorCamera.fov;camera.near=editorCamera.near;orbit.target.copy(editorCamera.target);document.body.classList.remove('driving');$('#drive').classList.remove('active');$('#edit').classList.add('active');$('#map-panel').classList.remove('open');$('#save').disabled=false;$('#export-glb').disabled=false;resize();}
function overview(){camera.fov=43;camera.near=1;const aspect=viewport.clientWidth/viewport.clientHeight;const distance=Math.max(330,150/(Math.tan(43*Math.PI/360)*aspect));camera.position.copy(new THREE.Vector3(-140,210,220).normalize().multiplyScalar(distance));orbit.target.set(0,0,0);camera.lookAt(orbit.target);camera.updateProjectionMatrix();}
function resize(){const w=viewport.clientWidth,h=viewport.clientHeight;renderer.setSize(w,h,false);camera.aspect=w/h;camera.updateProjectionMatrix();}
function drawMap(){const c=$('#minimap'),ctx=c.getContext('2d'),sx=x=>300+x*2.3,sy=y=>255-y*2.3;ctx.clearRect(0,0,c.width,c.height);ctx.fillStyle='#658b69';ctx.beginPath();ctx.ellipse(300,255,260,215,0,0,Math.PI*2);ctx.fill();for(const r of nav.roads){ctx.strokeStyle=r.type==='race'?'#27383d':'#d1d1b7';ctx.lineWidth=r.width*1.2;ctx.beginPath();r.samples.forEach(([x,y],i)=>i?ctx.lineTo(sx(x),sy(y)):ctx.moveTo(sx(x),sy(y)));ctx.stroke();}for(const z of nav.zones){ctx.fillStyle=z.color;ctx.beginPath();ctx.arc(sx(z.x),sy(z.y),8,0,Math.PI*2);ctx.fill();ctx.fillStyle='#f2f6ed';ctx.font='11px sans-serif';ctx.textAlign='center';ctx.fillText(z.name,sx(z.x),sy(z.y)-12);}if(driving){const v=driving.vehicle,p=v.position;ctx.save();ctx.translate(sx(p.x),sy(-p.z));ctx.rotate(Math.atan2(v.forward.z,v.forward.x));ctx.fillStyle='#fff';ctx.strokeStyle='#233c40';ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(11,0);ctx.lineTo(-8,-7);ctx.lineTo(-5,0);ctx.lineTo(-8,7);ctx.closePath();ctx.fill();ctx.stroke();ctx.restore();}}
function showAchievements(){if(!gameplay)return;const list=$('#awards-list');list.replaceChildren();for(const award of gameplay.achievements.view()){const row=document.createElement('p'),title=document.createElement('strong'),description=document.createElement('small');title.textContent=(award.unlocked?'✓ ':'○ ')+award.title;description.textContent=award.description+' · '+Math.min(award.progress,award.target)+' / '+award.target;row.append(title,description);list.append(row);}$('#awards-dialog').showModal();}
function updateGameplay(){if(!gameplay)return;const h=gameplay.hud(),div=$('#gameplay-hud');const text=[h.headline,h.timer,...h.lines,h.notice?.title].filter(Boolean).join(' · ');if(div.textContent!==text)div.textContent=text;$('#interact-action').hidden=!h.prompt;$('#interact-action').textContent=h.prompt+' · E';}
async function init(){renderer=new THREE.WebGLRenderer({canvas,antialias:true});renderer.setPixelRatio(Math.min(devicePixelRatio,1.5));renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.05;
 scene=new THREE.Scene();scene.background=new THREE.Color('#458d9d');camera=new THREE.PerspectiveCamera(43,1,1,1400);orbit=new OrbitControls(camera,canvas);orbit.enableDamping=true;orbit.maxDistance=600;orbit.minDistance=2;orbit.maxPolarAngle=Math.PI*.49;overview();
 scene.add(new THREE.HemisphereLight(0xe6f4ed,0x727955,1.65));const sun=new THREE.DirectionalLight(0xffe8c5,2.5);sun.position.set(-90,160,90);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);Object.assign(sun.shadow.camera,{left:-120,right:120,top:110,bottom:-110,near:1,far:420});sun.shadow.bias=-.0003;sun.shadow.normalBias=.08;scene.add(sun);scene.add(sun.target);
 const [gltf,data]=await Promise.all([new GLTFLoader().loadAsync('../exports/AlejandroWorld.glb'),fetch('../exports/navigation.json').then(r=>r.json()),RAPIER.init()]);root=gltf.scene;nav=data;scene.add(root);root.traverse(o=>{if(o.isMesh){o.castShadow=!o.userData.unselectable;o.receiveShadow=true;for(const mat of Array.isArray(o.material)?o.material:[o.material]){mat.side=THREE.DoubleSide;if(mat.map?.name.includes('palette')){mat.map.magFilter=THREE.NearestFilter;mat.map.minFilter=THREE.NearestFilter;}}}if(o.userData.runtime_collider)o.visible=false;});
 root.updateMatrixWorld(true);root.traverse(o=>{if(o.userData.aw_loop)loopOriginalMatrix=o.matrixWorld.clone();});mixer=new THREE.AnimationMixer(root);gltf.animations.forEach(a=>mixer.clipAction(a).play());$('#load-message').textContent='Preparando los assets funcionales de World2…';catalog=await loadWorld2Catalog();editor=new WorldEditor(scene,root,camera,renderer,orbit,notice,catalog);editor.animationClips=gltf.animations;await editor.restore();resize();new ResizeObserver(resize).observe(viewport);ready=true;$('#loading').remove();
 $('#drive').onclick=enterDrive;$('#edit').onclick=exitDrive;$('#overview').onclick=overview;$('#simulate').onclick=()=>{if(mode!=='edit')return;if(simulating){stopSimulation();editor.setEnabled(true);}else{startSimulation();editor.setEnabled(false);}};$('#reset-sim').onclick=resetSimulation;$('#close-map').onclick=()=>$('#map-panel').classList.remove('open');
 $('#close-awards').onclick=()=>$('#awards-dialog').close();$('#interact-action').onclick=()=>gameplay?.interact();$('#help').onclick=()=>$('#help-dialog').showModal();$('#close-help').onclick=()=>$('#help-dialog').close();
 let previous=performance.now(),fpsTime=previous,frames=0;function frame(now){requestAnimationFrame(frame);const dt=Math.min(.07,(now-previous)/1000);previous=now;if(simulating){driving?.inputs.update();accumulator+=dt;let steps=0;while(accumulator>=1/60&&steps<5){if(driving)driving.fixed();else physics.step();accumulator-=1/60;steps++;}if(steps===5)accumulator=0;physics.render(accumulator*60);mixer.update(dt);if(simulationContext){simulationContext.ticker.elapsed+=dt;simulationContext.ticker.delta=dt;simulationContext.ticker.events.trigger('tick');}if(driving){driving.render(dt,accumulator*60);const p=driving.vehicle.position;sun.position.copy(p).add(new THREE.Vector3(-70,130,80));sun.target.position.copy(p);}}else{orbit.update();}
 renderer.render(scene,camera);frames++;if(now-fpsTime>500){$('#performance').textContent=Math.round(frames*1000/(now-fpsTime))+' FPS · '+renderer.info.render.calls+' calls';frames=0;fpsTime=now;if(driving){$('#speed').textContent=String(Math.round(driving.vehicle.speedKmh)).padStart(2,'0');$('#surface').textContent=driving.loop.active?'LOOP · ADHERENCIA LOCAL':driving.vehicle.wheels.items.some(w=>w.groundCollider?.userData.surface_type==='ice')?'ICE · LOW GRIP':driving.nearest().name.toUpperCase();}updateGameplay();if($('#map-panel').classList.contains('open'))drawMap();}}
 requestAnimationFrame(frame);
}
addEventListener('keydown',e=>{if(e.target.matches('input,textarea,select')||$('#help-dialog').open)return;if(mode==='drive'){if(['Space','Tab','ArrowUp','ArrowDown','ArrowLeft','ArrowRight'].includes(e.code))e.preventDefault();keys.add(e.code);if(e.repeat)return;if(e.code==='Escape'){if(gameplay?.active())gameplay.active().exit();else exitDrive();}if(e.code==='Tab'){$('#map-panel').classList.toggle('open');drawMap();}}});addEventListener('keyup',e=>keys.delete(e.code));addEventListener('blur',()=>keys.clear());
init().catch(e=>{console.error(e);$('#load-message').textContent='Error: '+e.message;});
