import fs from 'node:fs';import * as THREE from 'three';import {readGLB} from '../../tests/read_glb.mjs';
const {scene,doc,nodes}=readGLB('exports/AlejandroWorld.glb');const rows=[];
for(const o of nodes){if(!o.isMesh&&!o.userData.editable_root)continue;const box=new THREE.Box3().setFromObject(o);if(box.isEmpty())continue;rows.push({name:o.name,id:o.userData.aw_id,category:o.userData.category,bounds:[box.min.toArray(),box.max.toArray()],scale:o.scale.toArray(),collision:!!o.userData.collision,surface:o.userData.surface_type,ground:!!o.userData.ground_surface,dynamic:o.userData.physics_mode==='DYNAMIC',source:o.userData.source_area||null,animated:!!o.userData.animated});}
const errors=[];for(const r of rows)if(r.scale.some(s=>!Number.isFinite(s)||Math.abs(s)<1e-5))errors.push({type:'INVALID_SCALE',name:r.name});
for(const i of doc.images??[])if(i.uri&&!i.uri.startsWith('data:'))errors.push({type:'EXTERNAL_TEXTURE',uri:i.uri});
const seen=new Set();for(const n of nodes){if(n.userData.aw_id){if(seen.has(n.userData.aw_id))errors.push({type:'DUPLICATE_ID',name:n.name});seen.add(n.userData.aw_id);}if(n.userData.collision&&n.isMesh){const a=n.geometry.attributes.position.array;if(a.some(v=>!Number.isFinite(v)))errors.push({type:'BAD_COLLISION',name:n.name});}}
const meshTransforms=new Map();let colliderTriangles=0;for(let i=0;i<nodes.length;i++){const o=nodes[i],n=doc.nodes[i];if(n.mesh!==undefined){const key=n.mesh+':'+o.matrixWorld.elements.map(x=>x.toFixed(5)).join(',');if(meshTransforms.has(key))errors.push({type:'DUPLICATE_MESH_TRANSFORM',name:o.name,other:meshTransforms.get(key)});else meshTransforms.set(key,o.name);}if(o.userData.collision){o.traverse(m=>{if(!m.isMesh)return;const p=m.geometry.attributes.position,idx=m.geometry.index?.array||Array.from({length:p.count},(_,j)=>j);colliderTriangles+=idx.length/3;const a=new THREE.Vector3(),b=new THREE.Vector3(),c=new THREE.Vector3();let bad=0;for(let j=0;j<idx.length;j+=3){a.fromBufferAttribute(p,idx[j]);b.fromBufferAttribute(p,idx[j+1]);c.fromBufferAttribute(p,idx[j+2]);if(b.sub(a).cross(c.sub(a)).lengthSq()<1e-16)bad++;}if(bad>0)errors.push({type:'DEGENERATE_COLLISION_FACES',name:o.name,count:bad});});}}
fs.writeFileSync('reports/v2-scene-bounds.json',JSON.stringify(rows));fs.writeFileSync('reports/v2-scene-validation.json',JSON.stringify({nodes:nodes.length,colliderTriangles,embeddedImages:doc.images?.length,errors},null,2));console.log({nodes:nodes.length,errors});

if(errors.length)process.exitCode=1;
